// User-facing strings for the mentor side of mentorship (one place, for later translation).

export const mentorStrings = {
  title: "Mentor dashboard",
  intro: "Answer session requests, keep your availability up to date and follow up after each session.",
  back: "← Mentor dashboard",
  create: {
    title: "Become a mentor",
    body: "Share your experience with community members. Create your mentor profile first; an admin verifies every mentor before they are listed.",
    cta: "Create mentor profile",
  },
  links: {
    profile: "Edit profile",
    availability: "Edit availability",
  },
  rating: (avg: string, count: number) => `${avg} ★ from ${count} ${count === 1 ? "rating" : "ratings"}`,
  noRating: "No ratings yet",
  verification: {
    pendingTitle: "Waiting for verification",
    pendingBody: "An admin is reviewing your mentor profile. You'll be listed and bookable once you're approved.",
    approvedTitle: "Verified mentor",
    approvedBody: "Members can find you and request sessions in your free slots.",
    paused: "You are not accepting bookings right now, so you are hidden from the mentor list.",
    rejectedTitle: "Verification was not approved",
    rejectedReason: (reason: string) => `Reason: ${reason}`,
    noteLabel: "Note for the admin (optional)",
    reRequest: "Request review again",
    sending: "Sending…",
    sent: "Sent for review.",
  },
  noAvailability: {
    title: "No availability yet",
    body: "Members can't book you until you add your weekly hours.",
    cta: "Add availability",
  },
  sessions: {
    requests: "Requests",
    requestsEmpty: "No requests are waiting for you.",
    upcoming: "Upcoming sessions",
    upcomingEmpty: "No confirmed sessions coming up.",
    past: "Past sessions",
    pastEmpty: "Nothing here yet.",
    with: (name: string) => `With ${name}`,
    someone: "A member",
    goal: "Their goal",
    noGoal: "No note given.",
    meetingLink: "Meeting link",
    open: "Open session",
    join: "Join meeting",
  },
  respond: {
    accept: "Accept",
    acceptTitle: "Accept this session",
    acceptBody: "Paste the Google Meet or Zoom link for this session. The mentee sees it once you confirm.",
    urlLabel: "Meeting link",
    urlPlaceholder: "https://meet.google.com/…",
    confirm: "Confirm session",
    decline: "Decline",
    declineTitle: "Decline this request",
    declineBody: "The mentee is told the request was declined.",
    reasonLabel: "Reason (optional)",
    confirmDecline: "Decline request",
    cancel: "Cancel",
    working: "Saving…",
    accepted: "Session confirmed.",
    declined: "Request declined.",
  },
  detail: {
    title: "Session",
    mentee: "Mentee",
    type: "Session type",
    when: "When",
    status: "Status",
    declineReason: "Reason given",
    cancelReason: "Cancellation reason",
    cancelSession: "Cancel session",
    cancelTitle: "Cancel this session?",
    cancelBody: "The mentee will see that you cancelled.",
    cancelReasonLabel: "Reason (optional)",
    confirmCancel: "Cancel session",
    keep: "Keep session",
    cancelled: "Session cancelled.",
    working: "Saving…",
  },
  feedback: {
    title: "Feedback",
    yours: "Your feedback",
    theirs: "From the mentee",
    theirRating: (rating: number) => `Rated ${rating} out of 5`,
    noneYet: "The mentee has not left feedback yet.",
    formTitle: "Leave feedback for the mentee",
    comment: "Comment (optional)",
    nextSteps: "Recommended next steps (optional)",
    nextStepsHint: "For example: courses to take, things to practise, people to talk to.",
    nextStepsLabel: "Recommended next steps",
    submit: "Send feedback",
    sending: "Sending…",
    sent: "Feedback sent.",
    opensLater: "You can leave feedback once the session has ended.",
  },
  notes: {
    title: "Private notes",
    onlyYou: "Only you can see these. The mentee never does.",
    empty: "No notes yet.",
    label: "New note",
    add: "Add note",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    confirmDelete: "Delete this note?",
    editLabel: "Edit note",
    saving: "Saving…",
  },
  profile: {
    titleNew: "Create your mentor profile",
    titleEdit: "Mentor profile",
    introNew: "This is what members see when they look for a mentor. Your phone number and email are never shown.",
    headline: "Headline",
    headlineHint: "For example: Senior backend engineer at a fintech.",
    bio: "About you (optional)",
    bioHint: "Your background and who you can help most. Up to 2,000 characters.",
    industries: "Industries (optional)",
    industriesHint: "Separate with commas, e.g. Software, Fintech. Up to 10.",
    years: "Years of experience",
    languages: "Languages you mentor in (optional)",
    languagesHint: "Separate with commas, e.g. English, Urdu. Up to 10.",
    city: "City (optional)",
    cityPlaceholder: "Choose a city",
    noCity: "No city",
    timezone: "Your time zone",
    timezoneHint: "Your availability is read in this time zone.",
    sessionTypes: "Session types you offer",
    duration: "Session length",
    minutes: (n: number) => `${n} minutes`,
    skills: "Expertise (optional)",
    skillsHint: "Up to 15 skills members can search by.",
    accepting: "Accepting bookings",
    acceptingHint: "Turn this off to take a break. You stay verified.",
    submitCreate: "Create profile",
    save: "Save profile",
    saving: "Saving…",
    saved: "Profile saved.",
  },
  availability: {
    title: "Availability",
    needProfile: "Create your mentor profile before adding availability.",
    explain: (timezone: string, minutes: number) =>
      `Times are in your time zone (${timezone}). Members can book ${minutes}-minute slots inside these hours, from 12 hours to 30 days ahead.`,
    weeklyTitle: "Weekly hours",
    weeklyEmpty: "No weekly hours yet. Add at least one so members can book you.",
    weekday: "Day",
    start: "From",
    end: "To",
    addRule: "Add hours",
    remove: "Remove",
    exceptionsTitle: "One-off changes",
    exceptionsBody: "Block a day or a few hours, or add extra time on a single date.",
    exceptionsEmpty: "No one-off changes.",
    date: "Date",
    kind: "What changes",
    kinds: {
      unavailable_day: "Unavailable all day",
      unavailable_range: "Unavailable for some hours",
      extra: "Extra hours",
    },
    wholeDay: "All day",
    addException: "Add change",
    saving: "Saving…",
    added: "Saved.",
    removed: "Removed.",
  },
  weekdays: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
  errors: {
    invalid: "Please check the form and try again.",
    headline: "Write a headline of 3 to 120 characters.",
    bio: "Keep this under 2,000 characters.",
    tags: "Use up to 10 short entries, separated by commas.",
    years: "Enter your years of experience (0 to 60).",
    timezone: "Choose your time zone.",
    sessionTypes: "Choose at least one session type.",
    skills: "Choose up to 15 skills.",
    time: "Enter a valid time.",
    timeOrder: "The end time must be after the start time.",
    date: "Choose a date.",
    timesRequired: "Enter both a start and an end time.",
    meetingUrl: "Add a meeting link that starts with https://.",
    reason: "Keep the reason under 500 characters.",
    feedbackEmpty: "Write a comment or next steps before sending.",
    comment: "Keep the comment under 1,000 characters.",
    nextSteps: "Keep next steps under 2,000 characters.",
    note: "Write a note of up to 2,000 characters.",
    reverifyNote: "Keep the note under 1,000 characters.",
    profile_required: "Create your mentor profile first.",
    onboarding_required: "Finish setting up your profile first.",
  },
} as const;
