// User-facing strings for relocation requests (one place, for later translation).

export const relocationStrings = {
  hub: {
    title: "Settle In",
    intro: "Moving to a new city for work? Ask verified community members there for help, and find a flat or flatmates.",
    newRequest: "Ask for help settling in",
    myRequests: "My relocation requests",
    emptyTitle: "No relocation requests yet",
    emptyBody: "Tell us where and when you're moving. Verified Settle-In Buddies in that city can then offer to help.",
    offersWaiting: (count: number) => (count === 1 ? "1 offer waiting for your reply" : `${count} offers waiting for your reply`),
    buddiesHelping: (count: number) => (count === 1 ? "1 buddy helping" : `${count} buddies helping`),
    moving: (date: string) => `Moving ${date}`,
    movingRange: (from: string, to: string) => `Moving between ${from} and ${to}`,
    more: "More for your move",
    links: [
      { href: "/flats", title: "Flats & rooms", body: "Browse listings from community members." },
      { href: "/flatmates", title: "Flatmates", body: "Find people to share a flat with." },
      { href: "/messages", title: "Messages", body: "Chat with buddies and listers who accepted you." },
    ],
  },
  form: {
    newTitle: "Ask for help settling in",
    newIntro:
      "Only verified Settle-In Buddies in your destination city can see this. Your phone number and email are never shown.",
    editTitle: "Edit this request",
    back: "Back to Settle In",
    city: "Which city are you moving to?",
    cityPlaceholder: "Choose a city",
    neighbourhoods: "Preferred neighbourhoods (optional)",
    noNeighbourhoods: "Choose a city to see its neighbourhoods.",
    moveFrom: "Move date",
    moveTo: "Latest move date (optional)",
    moveToHint: "Fill this in if your move date is a range.",
    workplaceAddress: "Workplace address (optional)",
    workplaceHint: "Helps buddies suggest areas with a short commute.",
    useLocation: "Use my current location",
    locating: "Finding your location…",
    pinSet: "Location pin added. It is saved when you submit.",
    pinSaved: "A location pin is saved for this request.",
    removePin: "Remove pin",
    locationDenied: "We couldn't get your location. You can still type the address.",
    budgetMin: "Monthly budget from (₹, optional)",
    budgetMax: "Monthly budget up to (₹, optional)",
    household: "Who is moving?",
    householdPlaceholder: "Choose one",
    needs: "What do you need help with?",
    note: "Short note (optional)",
    noteHint: "Anything a buddy should know. Up to 1,000 characters. Don't include your phone number.",
    sameGender: "Only buddies of my gender",
    sameGenderHint: "Your request is then shown only to buddies of the same gender as you.",
    create: "Post request",
    save: "Save changes",
    saving: "Saving…",
    saved: "Request saved.",
  },
  detail: {
    title: (city: string) => `Moving to ${city}`,
    posted: (when: string) => `Posted ${when}`,
    budget: "Budget",
    household: "Household",
    needs: "Help needed",
    areas: "Preferred areas",
    workplace: "Workplace",
    note: "Note",
    sameGender: "Shown only to buddies of your gender",
    offersTitle: "Offers of help",
    noOffersTitle: "No offers yet",
    noOffersBody: "Verified buddies in this city can see your request. You'll find their offers here.",
    noOffersClosed: "Nobody offered help on this request.",
    accept: "Accept",
    decline: "Decline",
    accepted: "Offer accepted. You can chat now.",
    declined: "Offer declined.",
    openChat: "Open chat",
    working: "Saving…",
    rating: (avg: string, count: number) => `${avg} ★ (${count})`,
    noRating: "No ratings yet",
    speaks: (languages: string) => `Speaks ${languages}`,
    closeTitle: "Finished with this request?",
    closeBody:
      "Mark it as settled once you have the help you need, then rate the buddies who helped. Offers still waiting will be declined.",
    settle: "I'm settled",
    cancel: "Cancel request",
    confirmSettle: "Mark this request as settled?",
    confirmSettleBody: "Offers still waiting will be declined. You can then rate the buddies who helped.",
    confirmCancel: "Cancel this request?",
    confirmCancelBody: "Buddies will no longer see it. Offers still waiting will be declined.",
    keep: "Keep it open",
    closed: "Request closed.",
    cancelled: "Request cancelled.",
    rateTitle: "Rate this buddy",
    ratingLabel: "Rating",
    ratingOption: (n: number) => (n === 1 ? "1 star" : `${n} stars`),
    comment: "Comment (optional)",
    submitRating: "Send rating",
    rated: "Thanks for rating.",
    yourRating: (n: number) => `You rated ${n} out of 5`,
  },
  errors: {
    city: "Choose a city.",
    moveFrom: "Enter your move date.",
    moveTo: "The latest date must be on or after the move date.",
    budget: "Enter whole rupees, e.g. 15000.",
    budgetRange: "The upper budget must be at least the lower budget.",
    household: "Choose who is moving.",
    needs: "Choose at least one thing you need help with.",
    note: "Keep the note under 1,000 characters.",
    workplaceAddress: "Keep the address under 300 characters.",
    comment: "Keep the comment under 1,000 characters.",
    invalid: "Some details are missing or invalid. Please check the form.",
    generic: "Something went wrong. Please try again.",
    not_authenticated: "Please sign in again.",
    onboarding_required: "Finish setting up your profile first.",
    open_request_limit: "You can have up to 3 open requests. Close one before posting another.",
    request_not_found: "That request no longer exists or is already closed.",
    offer_not_found: "That offer no longer exists.",
    offer_already_decided: "You already replied to this offer.",
    request_closed: "This request is closed.",
    blocked: "You can't accept this offer because one of you has blocked the other.",
    request_not_closed: "Close the request before rating a buddy.",
    offer_not_accepted: "You can only rate a buddy whose offer you accepted.",
    rating_required: "Choose a rating from 1 to 5.",
    comment_too_long: "Keep the comment under 1,000 characters.",
    already_rated: "You've already rated this buddy for this request.",
  },
} as const;
