// User-facing strings for the admin users screen.
export const usersStrings = {
  title: "Users",
  description: "Search members by name. Suspending hides their content and stops them posting or messaging.",
  searchLabel: "Name",
  searchPlaceholder: "Search by name",
  search: "Search",
  suspendedOnly: "Suspended only",
  empty: "No users match.",
  hint: "Type at least 2 letters of a name, or tick Suspended only.",
  joined: (date: string) => `Joined ${date}`,
  noCity: "No city",
  noRoles: "No roles yet",
  suspended: "Suspended",
  suspend: "Suspend",
  unsuspend: "Lift suspension",
  suspendTitle: (name: string) => `Suspend ${name}?`,
  suspendBody: "They can no longer post, message, book or be seen, and they are blocked from signing in.",
  unsuspendTitle: (name: string) => `Restore ${name}?`,
  unsuspendBody: "Their account and content become visible again and they can sign in.",
  reasonLabel: "Reason (kept in the audit log)",
  reasonRequired: "Give a reason of at least 5 characters.",
  confirm: "Confirm",
  cancel: "Cancel",
  working: "Saving…",
  suspendedDone: "User suspended and blocked from signing in.",
  suspendedAppOnly: "Suspended in the app; sign-in could not be blocked because the admin function is not deployed.",
  restoredDone: "Suspension lifted.",
  restoredAppOnly: "Restored in the app; the sign-in block could not be changed because the admin function is not deployed.",
  errors: {
    admin_only: "Only admins can do this.",
    cannot_suspend_self: "You cannot suspend your own account.",
    cannot_suspend_admin: "Admins cannot be suspended.",
    reason_required: "A reason is required to suspend a user.",
    user_not_found: "That user no longer exists.",
    generic: "Could not save. Please try again.",
  },
} as const;
