// User-facing strings for the admin places and area guide screens.
export const placesAdminStrings = {
  back: "Admin",
  working: "Saving…",
  saved: "Saved.",
  cancel: "Cancel",
  places: {
    title: "Places",
    description: "Add, edit, verify and hide places in the directory, and review suggestions from members.",
    add: "Add place",
    empty: "No places match these filters.",
    count: (n: number) => (n === 1 ? "1 place" : `${n} places`),
    verified: "Verified",
    unverified: "Not verified",
    hidden: "Hidden",
    edit: "Edit",
    verify: "Verify",
    unverify: "Remove verification",
    hide: "Hide",
    unhide: "Show again",
    delete: "Delete",
    deleteQuestion: "Delete this place?",
    deleteBody: "The place, its photos and any suggestions about it are removed for good. Hide it instead if you may want it back.",
    deleted: "Place deleted.",
    previous: "Previous",
    next: "Next",
    page: (page: number, pages: number) => `Page ${page} of ${pages}`,
  },
  filters: {
    heading: "Filter places",
    search: "Name",
    city: "City",
    anyCity: "All cities",
    type: "Type",
    anyType: "All types",
    state: "Status",
    anyState: "Any status",
    apply: "Apply",
    clear: "Clear",
  },
  suggestions: {
    title: "Suggestions waiting",
    empty: "No suggestions are waiting.",
    newPlace: "New place",
    correction: "Correction",
    correctionFor: "Correction for",
    from: "From",
    note: "Note from the member",
    reject: "Reject",
    unknownMember: "A member",
    fields: {
      name: "Name",
      place_type: "Type",
      city_id: "City",
      neighbourhood_id: "Area",
      address: "Address",
      timings: "Timings",
      phone: "Phone",
      website: "Website",
      notes: "Notes",
      lat: "Latitude",
      lng: "Longitude",
    } as Record<string, string>,
  },
  form: {
    newTitle: "Add a place",
    editTitle: "Edit place",
    name: "Name",
    type: "Type",
    city: "City",
    chooseCity: "Choose a city",
    area: "Area",
    noArea: "No area",
    address: "Address",
    phone: "Phone (public contact of the institution)",
    website: "Website",
    websiteHint: "Starts with http:// or https://",
    timings: "Timings",
    timingsHint: "Prayer, majlis or opening times.",
    notes: "Notes",
    verified: "Verified",
    verifiedHint: "Only verified places appear in the public directory and on the map.",
    location: "Location",
    mapLabel: "Pick the place on the map",
    latitude: "Latitude",
    longitude: "Longitude",
    coordsHint: "Set by the map pin. You can also type the coordinates.",
    save: "Save place",
    viewPublic: "Open public page",
  },
  photos: {
    title: "Photos",
    hint: "JPEG, PNG or WebP, up to 5 MB each. Up to 20 photos.",
    add: "Add photos",
    uploading: "Uploading…",
    remove: "Remove",
    removed: "Photo removed.",
    alt: (name: string, n: number) => `${name}, photo ${n}`,
    empty: "No photos yet.",
    errors: {
      type: "Use a JPEG, PNG or WebP image.",
      size: "That photo is too large (5 MB at most after resizing).",
      limit: "A place can have up to 20 photos.",
      upload: "Could not upload the photo. Please try again.",
    },
  },
  areas: {
    title: "Area guides",
    description: "Write the guide for each neighbourhood and moderate community tips.",
    none: "No guide",
    draft: "Draft",
    published: "Published",
    tips: (n: number) => (n === 1 ? "1 tip" : `${n} tips`),
    empty: "No neighbourhoods yet.",
  },
  guide: {
    title: (area: string) => `Guide for ${area}`,
    summary: "Summary",
    rentHeading: "Typical monthly rent (rupees)",
    rentHint: "Leave a row empty to leave that type out.",
    min: "From",
    max: "To",
    commute: "Commute notes",
    safety: "Safety notes",
    halalFood: "Halal food notes",
    published: "Published",
    publishedHint: "Published guides are visible to everyone, including signed-out visitors.",
    save: "Save guide",
    delete: "Delete guide",
    deleteQuestion: "Delete this guide?",
    deleteBody: "The guide text is removed. Community tips stay.",
    deleted: "Guide deleted.",
    viewPublic: "Open public page",
  },
  tips: {
    title: "Community tips",
    empty: "No tips for this area yet.",
    hide: "Hide",
    restore: "Restore",
    hiddenBadge: "Hidden",
    deletedBadge: "Deleted by author",
    upvotes: (n: number) => (n === 1 ? "1 upvote" : `${n} upvotes`),
    unknownAuthor: "A member",
  },
  listingTypes: {
    entire_flat: "Entire flat",
    private_room: "Private room",
    shared_room: "Shared room",
    pg_hostel: "PG / hostel",
  },
  errors: {
    admin_only: "Only admins can do this.",
    note_too_long: "The note is too long (1000 characters at most).",
    suggestion_not_found: "That suggestion no longer exists.",
    suggestion_already_decided: "Someone already decided this suggestion.",
    suggestion_incomplete: "This suggestion is missing a name, type or city, so it cannot be approved.",
    target_not_found: "That item no longer exists.",
    invalid_target: "That item cannot be hidden.",
    generic: "Could not save. Please try again.",
    invalid: "Please check the form and try again.",
    notFound: "That item no longer exists, or you are not allowed to change it.",
    name: "Enter a name of 2 to 150 characters.",
    type: "Choose a type.",
    city: "Choose a city.",
    area: "Choose an area in the selected city.",
    address: "The address is too long (300 characters at most).",
    phone: "Enter a phone number using digits, spaces, + - ( ).",
    website: "Enter a web address starting with http:// or https://.",
    timings: "The timings are too long (1000 characters at most).",
    notes: "The notes are too long (2000 characters at most).",
    location: "Set the location on the map, or enter a valid latitude and longitude.",
    summary: "Write a summary of 1 to 5000 characters.",
    guideNote: "Each note can be 2000 characters at most.",
    rent: "Enter whole rupee amounts, with \"To\" not lower than \"From\".",
    photoPath: "That photo could not be saved.",
  },
} as const;
