// User-facing strings for chat (one place, for later translation).
import type { ConversationContext } from "./types";

export const contextLabels: Record<ConversationContext, string> = {
  relocation_offer: "Settle-In buddy",
  flat_contact: "Flat enquiry",
  flatmate_connection: "Flatmate",
};

export const chatStrings = {
  title: "Messages",
  loadingList: "Loading your messages",
  loadingChat: "Loading the conversation",
  unavailableUser: "Unavailable user",
  you: "You",
  photo: "Photo",
  noMessagesYet: "No messages yet",
  unread: (count: number) => `${count} unread`,
  emptyTitle: "No conversations yet",
  emptyBody:
    "A chat opens when a buddy offer, a flat contact request or a flatmate request is accepted. You can't message someone before that.",
  emptyLinks: { settleIn: "Settle In", flats: "Flats & rooms", flatmates: "Flatmates" },
  back: "All messages",
  notFoundTitle: "Conversation not found",
  notFoundBody: "It may not exist, or you are not part of it.",
  threadLabel: "Conversation messages",
  threadEmpty: "Say salaam to start the conversation.",
  loadEarlier: "Load earlier messages",
  loadingEarlier: "Loading…",
  composerLabel: "Message",
  composerPlaceholder: "Write a message",
  composerHint: "Enter to send, Shift+Enter for a new line",
  send: "Send",
  sending: "Sending…",
  attach: "Attach a photo",
  uploading: "Uploading photo…",
  removeMessage: "Delete message",
  deleteConfirm: "Delete this message for everyone?",
  deleted: "Message deleted.",
  reportMessage: "Report",
  reportUser: "Report user",
  photoAlt: "Photo sent in the chat",
  photoLoading: "Loading photo…",
  photoUnavailable: "Photo unavailable",
  openPhoto: "Open photo in a new tab",
  blockedByMe: "You blocked this person. Unblock them to send messages.",
  blocked: "You can't message this person.",
  errors: {
    generic: "We couldn't do that. Please try again.",
    invalid: "Write a message of up to 2,000 characters or attach a photo.",
    tooLong: "Keep messages under 2,000 characters.",
    signedOut: "Please sign in again.",
    load: "We couldn't load earlier messages. Please try again.",
    imageType: "Choose a JPEG, PNG or WebP image.",
    imageSize: "That photo is too large. Choose one under 5 MB.",
    upload: "We couldn't upload the photo. Please try again.",
    not_sender: "We couldn't send that message. Please sign in again.",
    not_participant: "You are not part of this conversation.",
    account_suspended: "Your account is suspended, so you can't send messages.",
    blocked: "You can't message this person.",
    invalid_attachment: "That photo could not be attached. Please try again.",
    empty_message: "Write a message or attach a photo.",
    rate_limit_exceeded: "You're sending messages too quickly. Wait a minute and try again.",
    message_not_found: "That message no longer exists.",
  },
} as const;
