// User-facing strings for the map page.
export const mapPageStrings = {
  title: "Map",
  intro: "Find flats close to a masjid or imambargah and to your workplace.",
  approxNote: "Flat locations are approximate; the exact address is shared after the lister accepts your request.",
  mapLabel: "Map of flats, masjids, imambargahs and other places",
  filters: {
    toggle: (count: number) => (count > 0 ? `Filters (${count})` : "Filters"),
    show: "Show filters",
    hide: "Hide filters",
    city: "City",
    allCities: "All cities",
    masjid: "Near a masjid or imambargah",
    masjidOff: "Any distance",
    masjidWithin: (km: number) => `Within ${km} km`,
    workplaceRadius: "Distance from my workplace",
    workplaceOff: "Any distance",
    workplaceWithin: (km: number) => `Within ${km} km`,
    workplaceRadiusHint: "Set your workplace first to use this.",
    rentMin: "Rent from (₹ a month)",
    rentMax: "Rent up to (₹ a month)",
    listingTypes: "Type of place to live",
    layers: "Places shown on the map",
    apply: "Apply filters",
    applying: "Searching…",
    reset: "Clear filters",
  },
  workplace: {
    title: "My workplace",
    none: "No workplace set.",
    set: "Workplace set.",
    setButton: "Set workplace",
    changeButton: "Change workplace",
    remove: "Remove",
    useLocation: "Use my current location",
    locating: "Finding your location…",
    locationDenied: "We could not read your location. You can place the pin on the map instead.",
    fromRequest: "Use the workplace from my relocation request",
    pickerLabel: "Pick your workplace on the map",
    done: "Use this location",
    cancel: "Cancel",
    privacy: "Your workplace is only used for this search. It is not saved or shown to anyone.",
  },
  results: {
    heading: "Flats",
    count: (n: number, total: number) =>
      total > n ? `Showing ${n} of ${total} flats` : n === 1 ? "1 flat" : `${n} flats`,
    emptyTitle: "No flats match these filters",
    emptyBody: "Try a larger distance, a higher rent, or a different city.",
    searchArea: "Search this area",
    searchingArea: "Searching this area…",
    areaActive: "Showing flats in the map area.",
    clearArea: "Show all matching flats",
    fromMasjid: (distance: string, name: string) => `${distance} from ${name}`,
    fromWorkplace: (distance: string) => `${distance} from your workplace`,
    view: "View flat",
    photoAlt: (title: string) => `Photo of ${title}`,
    markerLabel: (title: string, rent: string) => `Flat: ${title}, ${rent}`,
    loading: "Updating results…",
  },
  place: {
    heading: "Selected place",
    open: "Open place page",
    close: "Close",
    markerLabel: (type: string, name: string) => `${type}: ${name}`,
    workplaceMarker: "Your workplace",
  },
  legend: {
    title: "Map key",
    flat: "Flat (approximate)",
    masjid: "Masjid or imambargah",
    place: "Other place",
    workplace: "Your workplace",
  },
  errors: {
    generic: "Could not load the map results. Please try again.",
    invalid: "Those filters are not valid.",
    signedOut: "Please sign in first.",
  },
} as const;
