// User-facing strings for applying, my applications and referrals (one place, for later translation).

export const applyStrings = {
  title: (jobTitle: string) => `Apply for ${jobTitle}`,
  backToJob: "Back to the job",
  deadline: (date: string) => `Applications close on ${date}`,
  closedTitle: "This job is no longer accepting applications",
  closedBody: "It may have been closed or the deadline has passed.",
  browseJobs: "Browse other jobs",
  alreadyAppliedTitle: "You've already applied for this job",
  viewApplication: "View my application",
  noCvTitle: "Upload a CV first",
  noCvBody: "You need at least one CV (PDF) on your job profile before you can apply.",
  goToProfile: "Go to my job profile",
  referredNote: "You were referred by a community member. The employer will see this on your application.",
  cvLegend: "Which CV do you want to send?",
  defaultCv: "Default",
  coverNote: "Cover note (optional)",
  coverNoteHint: "A few lines on why you're a good fit. Up to 2,000 characters.",
  questionsTitle: "Questions from the employer",
  required: "required",
  optional: "optional",
  submit: "Send application",
  submitting: "Sending…",
  retryWithoutReferral: "Apply without the referral",
  errors: {
    cv: "Choose a CV.",
    coverNote: "Keep the cover note under 2,000 characters.",
    answerRequired: "Please answer this question.",
    answerTooLong: "Keep answers under 1,000 characters.",
    invalid: "Some details are missing or invalid. Please check the form.",
    generic: "We couldn't send your application. Please try again.",
    job_not_open: "This job is no longer accepting applications.",
    deadline_passed: "The deadline for this job has passed.",
    already_applied: "You've already applied for this job.",
    invalid_cv: "That CV could not be found. Choose another one.",
    required_answer_missing: "Please answer all the required questions.",
    invalid_referral: "That referral link is no longer valid. You can still apply without it.",
    cannot_apply_to_own_company: "You can't apply to a job at your own company.",
    onboarding_required: "Finish setting up your profile before applying.",
    not_authenticated: "Please sign in again.",
  },
} as const;

export const applicationsStrings = {
  title: "My applications",
  emptyTitle: "No applications yet",
  emptyBody: "When you apply for a job it will show up here with its status.",
  findJobs: "Find jobs",
  appliedOn: (date: string) => `Applied ${date}`,
  referred: "Referred",
  pickInterview: "Pick an interview time",
  interviewOn: (when: string) => `Interview: ${when}`,
  back: "All applications",
  viewJob: "View the job",
  timelineTitle: "Status history",
  timelineStart: "Application sent",
  timelineChange: (to: string) => `Moved to ${to}`,
  detailsTitle: "What you sent",
  cv: "CV",
  cvRemoved: "CV no longer available",
  coverNote: "Cover note",
  noCoverNote: "No cover note",
  answers: "Your answers",
  interviewTitle: "Interview",
  interviewPickHint: "The employer proposed these times. Pick the one that suits you.",
  interviewConfirmed: "Confirmed interview time",
  pickSlot: "Pick this time",
  picking: "Saving…",
  slotPicked: "Interview time confirmed.",
  where: "Where",
  withdraw: "Withdraw application",
  withdrawTitle: "Withdraw this application?",
  withdrawBody: "The employer will no longer be able to see your CV for this job. You can't undo this.",
  withdrawConfirm: "Yes, withdraw",
  withdrawing: "Withdrawing…",
  cancel: "Keep my application",
  withdrawn: "Application withdrawn.",
  errors: {
    generic: "Something went wrong. Please try again.",
    slot_not_found: "That interview time is no longer available.",
    slot_not_available: "That interview time is no longer available.",
    application_closed: "This application is closed.",
    application_not_found: "We couldn't find that application.",
  },
} as const;

export const referralsStrings = {
  title: "Refer someone",
  intro:
    "Share a referral link for a job where you work. When someone applies through it, the employer sees they were referred by you.",
  workTitle: "Where I work",
  workEmpty: "Add the organisation you work at. You can refer people to its jobs once it posts them on NextStep.",
  companyLabel: "Company on NextStep",
  companyPlaceholder: "Choose a company",
  noCompanies: "No verified companies on NextStep yet. Type your organisation's name instead.",
  notListed: "My organisation isn't listed",
  pickFromList: "Choose from the list instead",
  organisationLabel: "Organisation name",
  organisationHint: "If your organisation joins NextStep later, you'll be linked to it automatically.",
  notOnNextStep: "Not on NextStep yet",
  inviteEmployer: "Referral links work once it posts jobs here. Ask your HR team to",
  inviteEmployerLink: "register it on NextStep",
  add: "Add",
  adding: "Adding…",
  remove: "Remove",
  removeLabel: (company: string) => `Remove ${company}`,
  confirmed: "Confirmed by the company",
  unconfirmed: "Not yet confirmed by the company",
  jobsTitle: (company: string) => `Open jobs at ${company}`,
  jobsEmpty: "No open jobs at this company right now.",
  createLink: "Create referral link",
  creating: "Creating…",
  noteLabel: "Note for the employer (optional)",
  notePlaceholder: "e.g. Worked with them for two years",
  linkLabel: "Referral link",
  copy: "Copy link",
  copied: "Copied",
  copyFailed: "Select the link and copy it.",
  deleteLink: "Delete link",
  deleteLabel: (job: string) => `Delete referral link for ${job}`,
  yourNote: (note: string) => `Your note: ${note}`,
  errors: {
    generic: "Something went wrong. Please try again.",
    duplicateAffiliation: "You've already added that organisation.",
    companyUnavailable: "That company isn't available.",
    organisationName: "Enter the organisation's name (2 to 120 characters).",
    affiliationLimit: "You can add up to 10 organisations. Remove one first.",
    affiliation_required: "Add this company under “Where I work” first.",
    job_not_open: "This job is no longer open.",
    note: "Keep the note under 500 characters.",
  },
} as const;
