// User-facing strings for the app shell and generic pages (kept in one place for later translation).
export const shellStrings = {
  brand: "NextStep",
  tagline: "NextStep: Learn. Earn. Grow.",
  home: "Home",
  soon: "Soon",
  comingSoon: "Coming soon",
  mainNav: "Main navigation",
  accountNav: "Account",
  openMenu: "Open account menu",
  addRole: "Add a role",
  adminLink: "Admin panel",
  signOut: "Sign out",
  signIn: "Log in",
  signUp: "Sign up",
  goToDashboard: "Go to dashboard",
  getStarted: "Get started",
  bottomNav: {
    home: "Home",
    "community-portal": "Earn",
    "career-development": "Learn",
    "location-gathering": "Grow",
    inbox: "Inbox",
  },
  inbox: "Messages",
  settings: "Settings",
  notifications: "Notifications",
  theme: { label: "Appearance", light: "Light", dark: "Dark", system: "Match device" },
  landing: {
    eyebrow: "For the Shia Muslim community in India",
    heroTitle: "Learn. Earn. Grow.",
    intro:
      "Find work with trusted employers, learn from experienced mentors, and settle into a new city close to masjids, imambargahs and people who can help.",
    browseJobs: "Browse jobs",
    heroNote: "Free to join. Sign up with your email and a password.",
    howHeading: "How it works",
    howSteps: [
      { title: "Create your profile", body: "Sign up in a minute and tell us your city." },
      { title: "Choose what you need", body: "A job, a mentor, a flat, a flatmate, or help settling into a new city." },
      { title: "Connect with verified people", body: "Employers, mentors and buddies are checked by the NextStep team before they appear." },
    ],
    sectionsHeading: "Three ways NextStep helps",
    sectionCards: {
      "community-portal": {
        benefit: "Jobs from verified employers, including community businesses. Apply in a few taps and track every application.",
        action: "Browse jobs",
        href: "/jobs",
      },
      "career-development": {
        benefit: "Book a session with an experienced professional for career advice, a CV review or a mock interview.",
        action: "Find a mentor",
        href: "/mentors",
      },
      "location-gathering": {
        benefit: "Moving for work? Find masjids and imambargahs nearby, area guides, flats, flatmates and a local buddy.",
        action: "Explore places",
        href: "/places",
      },
    },
    latestJobsHeading: "Latest jobs",
    seeAllJobs: "See all jobs",
    placesTitle: "Masjids & imambargahs",
    placesBody: "A directory of Shia masjids, imambargahs and community places in each city, checked by the NextStep team.",
    placesAction: "Open the directory",
    guidesAction: "Read area guides",
    trustHeading: "Safe by design",
    trustPoints: [
      { title: "Verified people", body: "Employers, mentors and Settle-In Buddies are reviewed by the NextStep team before they appear." },
      { title: "Your contact details stay private", body: "Phone numbers and emails are never shown publicly. You talk through in-app chat." },
      { title: "Addresses only after you agree", body: "A flat's exact address is shared only after the lister accepts your request." },
      { title: "Report and block", body: "Report or block anyone, any listing or any message. Our team reviews every report." },
    ],
    footerLinks: [
      { label: "Jobs", href: "/jobs" },
      { label: "Places", href: "/places" },
      { label: "Area guides", href: "/areas" },
      { label: "LEAP", href: "/leap" },
      { label: "Log in", href: "/sign-in" },
      { label: "Sign up", href: "/sign-up" },
    ],
    footerNav: "Footer",
    footerNote: "Built for the community · India",
  },
  home_: {
    greeting: (name: string) => (name ? `Assalamu alaikum, ${name}` : "Assalamu alaikum"),
    today: (date: string) => `Today is ${date}.`,
    nextStepsHeading: "Your next steps",
    nextStepsEmpty: "You're all caught up. Explore a section below.",
    steps: {
      unread: (n: number) => (n === 1 ? "You have 1 unread message" : `You have ${n} unread messages`),
      unreadAction: "Open messages",
      upcoming: (n: number) => (n === 1 ? "You have 1 upcoming mentor session" : `You have ${n} upcoming mentor sessions`),
      upcomingAction: "View sessions",
      uploadCv: "Upload your CV so you can apply to jobs",
      uploadCvAction: "Add CV",
      completeProfile: "Finish your job profile to get better recommendations",
      completeProfileAction: "Open profile",
      verificationPending: (kind: string) => `${kind} verification is waiting for review`,
      verificationRejected: (kind: string) => `${kind} verification was not approved`,
      noRoles: "Tell us what you're here for to unlock the right tools",
      noRolesAction: "Choose",
    },
    shortcutsHeading: "Explore",
    yourRoles: "Your roles",
    noRoles: "You haven't chosen what you're here for yet.",
    verificationHeading: "Verification",
    verificationKinds: {
      company: "Company",
      mentor: "Mentor",
      buddy: "Settle-In Buddy",
      flat_lister_id: "Flat lister ID badge",
    } as Record<string, string>,
    verificationStatus: {
      pending: "Pending review — an admin will check your details soon.",
      approved: "Approved — you're verified.",
      rejected: "Not approved. Contact support for details.",
    } as Record<string, string>,
    statusBadge: { pending: "Pending", approved: "Approved", rejected: "Rejected" } as Record<string, string>,
    openSection: "Open",
  },
  sectionPage: {
    available: "Open",
    roleOnly: "For your role",
  },
  suspended: {
    title: "Your account is suspended",
    body: "You can't use NextStep while your account is suspended. Please contact support.",
  },
  admin: {
    title: "Admin panel",
    body: "Verification, moderation, places, LEAP and analytics tools arrive in Phase 6.",
  },
  errors: {
    title: "Something went wrong",
    body: "We couldn't load this page. Please try again.",
    retry: "Try again",
    notFoundTitle: "Page not found",
    notFoundBody: "The page you're looking for doesn't exist or has moved.",
    backHome: "Back to home",
  },
} as const;
