// User-facing strings for area guides and community tips.
export const areaStrings = {
  index: {
    title: "Area guides",
    intro: "Get to know a neighbourhood before you move: rents, commute, halal food, and the masjids and imambargahs nearby.",
    hasGuide: "Guide",
    emptyTitle: "No areas yet",
    emptyBody: "Neighbourhoods will appear here once they are added.",
    noAreas: "No neighbourhoods listed for this city yet.",
    loading: "Loading area guides",
  },
  guide: {
    notFoundTitle: "Area not found",
    notFoundBody: "We couldn't find that neighbourhood. It may have been renamed.",
    backToAreas: "All area guides",
    noGuideTitle: "This guide hasn't been written yet",
    noGuideBody: "You can still see nearby places and tips from community members below.",
    about: "About this area",
    rent: "Typical rent",
    rentNote: "Rough monthly ranges. Actual rents vary by building and season.",
    commute: "Getting around",
    safety: "Safety",
    halalFood: "Halal food",
    worship: "Masjids and imambargahs nearby",
    worshipEmpty: "No verified masjid or imambargah is listed within 3 km yet.",
    otherPlaces: "Other places nearby",
    otherPlacesEmpty: "No other verified places are listed within 3 km yet.",
    noCentre: "Nearby places can't be shown because this area has no map location yet.",
    mapLabel: (area: string) => `Map of places near ${area}`,
    seeOnMap: "Open the map",
    findFlats: "Find flats in this city",
    signInForFlats: "Sign in to find flats",
    allPlaces: "Browse all places",
    updated: (date: string) => `Updated ${date}`,
    loading: "Loading area guide",
  },
  listingTypes: {
    entire_flat: "Entire flat",
    private_room: "Private room",
    shared_room: "Shared room",
    pg_hostel: "PG / hostel",
  },
  tips: {
    title: "Community tips",
    intro: "Short tips from verified Settle-In Buddies who live here.",
    empty: "No tips yet for this area.",
    anonymousAuthor: "Community member",
    you: "You",
    upvote: "Helpful",
    upvoted: "Marked helpful",
    upvoteCount: (count: number) => (count === 1 ? "1 person found this helpful" : `${count} people found this helpful`),
    remove: "Delete",
    removeConfirm: "Delete this tip?",
    removed: "Tip deleted.",
    report: "Report",
    signInPrompt: "Sign in to mark tips as helpful.",
    signIn: "Sign in",
    buddyOnly: "Tips are posted by verified Settle-In Buddies.",
    becomeBuddy: "Become a buddy",
    form: {
      label: "Share a tip about this area",
      placeholder: "For example: the best time to catch the local train, or where to find good halal food.",
      hint: "5 to 500 characters. Plain text only.",
      submit: "Post tip",
      submitting: "Posting…",
      posted: "Tip posted.",
    },
  },
  errors: {
    invalid: "Please check what you entered.",
    notSignedIn: "Please sign in first.",
    tipLength: "A tip must be 5 to 500 characters.",
    buddyRequired: "Only verified Settle-In Buddies can post tips.",
    generic: "Something went wrong. Please try again.",
    db: {
      verified_buddy_required: "Only verified Settle-In Buddies can post tips.",
      own_tip: "You can't mark your own tip as helpful.",
      tip_not_found: "That tip is no longer available.",
      account_suspended: "Your account is suspended.",
      rate_limit_exceeded: "You're doing that too often. Please try again later.",
    },
  },
} as const;
