// User-facing strings for the seeker job profile (kept in one place for later Urdu/Hindi translation).
export const seekerStrings = {
  pageTitle: "My job profile & CV",
  pageIntro: "Employers see this only when you apply to one of their jobs.",
  save: "Save",
  saving: "Saving…",
  saved: "Saved",
  cancel: "Cancel",
  edit: "Edit",
  delete: "Delete",
  deleting: "Deleting…",
  notSet: "Not set",
  completeness: {
    title: "Finish your profile",
    done: "Your profile is complete. Nice work.",
    intro: "Employers respond more to complete profiles. Still to add:",
    basics: "A headline",
    skills: "At least one skill",
    experience: "Work experience",
    education: "Education",
    cv: "A CV (needed to apply)",
  },
  basics: {
    title: "About your work",
    headline: "Headline",
    headlineHint: "One line, e.g. “Accountant with 3 years in GST and Tally”.",
    summary: "Summary",
    summaryHint: "A short introduction: what you do and what you're looking for.",
    experienceLevel: "Experience level",
    workMode: "Preferred way of working",
    noPreference: "No preference",
    cities: "Cities you'd like to work in",
    languages: "Languages",
    languagesHint: "Separate with commas, e.g. Urdu, Hindi, English.",
    linkedin: "LinkedIn link",
    portfolio: "Portfolio or website link",
    linkHint: "Must start with https://",
    relocate: "I'm open to moving to another city",
  },
  skills: {
    title: "Skills",
    hint: "Add up to 15 skills. Job recommendations use these.",
    label: "Add a skill",
  },
  experience: {
    title: "Work experience",
    empty: "No work experience added yet.",
    add: "Add experience",
    editTitle: "Edit experience",
    jobTitle: "Job title",
    company: "Company",
    start: "Start date",
    end: "End date",
    current: "I work here now",
    description: "What you did (optional)",
    present: "Present",
    confirmDelete: "Delete this experience?",
  },
  education: {
    title: "Education",
    empty: "No education added yet.",
    add: "Add education",
    editTitle: "Edit education",
    institution: "School, college or university",
    degree: "Degree or course",
    field: "Field of study (optional)",
    startYear: "Start year",
    endYear: "End year",
    confirmDelete: "Delete this education entry?",
  },
  salary: {
    title: "Expected salary",
    intro: "Private by default. Only you can see it unless you choose to share it.",
    min: "Minimum (₹ lakh a year)",
    max: "Maximum (₹ lakh a year)",
    share: "Share with employers I apply to",
    shareHint: "When off, employers never see your expected salary.",
  },
  cv: {
    title: "CVs",
    intro: "PDF only, up to 5 MB each. You can keep up to 5 and choose one when you apply.",
    empty: "No CV uploaded yet. You need one to apply for jobs.",
    upload: "Upload a CV (PDF)",
    uploading: "Uploading…",
    default: "Default",
    makeDefault: "Make default",
    view: "View",
    confirmDelete: "Delete this CV?",
    uploaded: "CV uploaded",
    deleted: "CV deleted",
  },
  errors: {
    generic: "Something went wrong. Please try again.",
    notSignedIn: "Please sign in again.",
    headline: "Keep the headline under 120 characters.",
    summary: "Keep the summary under 2,000 characters.",
    cities: "Choose up to 10 cities.",
    languages: "Add up to 10 languages, each under 40 characters.",
    url: "Enter a full link starting with https://",
    skills: "Choose up to 15 skills.",
    required: "This field is required.",
    tooLong: "That's too long.",
    date: "Enter a valid date.",
    endBeforeStart: "The end can't be before the start.",
    year: "Enter a year between 1950 and 2100.",
    salaryNumber: "Enter an amount in lakh, e.g. 6 or 7.5.",
    salaryOrder: "The minimum can't be more than the maximum.",
    cvType: "Only PDF files can be uploaded.",
    cvSize: "That file is larger than 5 MB.",
    cvLimit: "You already have 5 CVs. Delete one to upload another.",
    cvInUse: "This CV is attached to an application and can't be deleted.",
    cvUpload: "The upload failed. Please try again.",
    cvOpen: "Could not open the CV. Please try again.",
  },
} as const;
