// User-facing strings for the employer applicant pipeline (one place, for later translation).
export const pipelineStrings = {
  backToDashboard: "Back to employer dashboard",
  backToPipeline: "Back to applicants",
  editJob: "Edit job",
  applicantsTitle: "Applicants",
  referredOnly: "Referred only",
  referred: "Referred",
  noApplicantsTitle: "No applicants yet",
  noApplicantsBody: "Applications will appear here as soon as people apply to this job.",
  noReferredApplicants: "No referred applicants for this job.",
  emptyColumn: "No one here yet",
  withdrawnTitle: "Withdrawn",
  withdrawnHint: "These people withdrew their application. Their profile and CV are no longer shared with you.",
  applied: (when: string) => `Applied ${when}`,
  viewApplicant: "View applicant",
  unnamedApplicant: "Applicant",
  statusLabel: "Stage",
  statusFor: (name: string) => `Stage for ${name}`,
  moved: (name: string, stage: string) => `${name} moved to ${stage}`,
  statusNoteLabel: "Private note (optional)",
  statusNoteHint: "Saved with this change. Only your company can see it.",
  updateStatus: "Update stage",
  updating: "Updating…",
  statusUpdated: "Stage updated",
  loadErrorTitle: "We couldn't load the applicants",
  loadErrorBody: "Please try again. If it keeps happening, come back in a few minutes.",
  retry: "Try again",

  profileTitle: "Profile",
  summary: "About",
  skills: "Skills",
  languages: "Languages",
  experience: "Experience",
  education: "Education",
  present: "Present",
  expectedSalary: "Expected salary",
  noProfile: "This applicant hasn't filled in a job profile yet.",
  coverNote: "Cover note",
  answers: "Screening answers",
  noAnswer: "No answer",
  referralTitle: "Referral",
  referredBy: (name: string) => `Referred by ${name}`,
  affiliationConfirmed: "Confirmed as working at your company",
  affiliationUnconfirmed: "Says they work at your company (not confirmed)",
  affiliationMissing: "No longer listed as working at your company",
  history: "Stage history",
  historyStart: "Applied",
  withdrawnNotice: "This application was withdrawn, so it can't be changed.",

  cvTitle: "CV",
  viewCv: "View CV",
  openingCv: "Opening…",
  cvHint: "Opens in a new tab. The link stops working after 10 minutes.",
  cvUnavailable: "The CV isn't available for this application.",

  notesTitle: "Private notes",
  notesHint: "Only your company can see these. The applicant never sees them.",
  noteLabel: "Add a note",
  addNote: "Add note",
  addingNote: "Adding…",
  noNotes: "No notes yet.",
  deleteNote: "Delete note",
  noteAdded: "Note added",
  noteDeleted: "Note deleted",
  unknownAuthor: "A team member",

  slotsTitle: "Interview slots",
  slotsHint: "Propose one or more times. The applicant picks one and the rest are cancelled.",
  slotDate: "Date",
  slotTime: "Start time",
  slotDuration: "Length",
  slotLocation: "Location or video link (optional)",
  slotLocationPlaceholder: "Office address or meeting link",
  minutes: (n: number) => `${n} minutes`,
  proposeSlot: "Propose time",
  proposing: "Proposing…",
  slotProposed: "Time proposed",
  slotCancelled: "Time cancelled",
  cancelSlot: "Cancel",
  noSlots: "No interview times proposed yet.",
  slotStatus: { proposed: "Proposed", selected: "Chosen by applicant", cancelled: "Cancelled" },

  errors: {
    not_company_member: "You don't have access to this application.",
    application_withdrawn: "This application was withdrawn and can't be moved.",
    invalid_status: "That stage isn't allowed.",
    slot_in_past: "Choose a time in the future.",
    application_closed: "This application is closed, so interviews can't be scheduled.",
    slot_limit_reached: "You can have up to 10 proposed times. Cancel one first.",
    invalidInput: "Please check the form and try again.",
    noteTooLong: "Notes can be up to 2,000 characters.",
    noteEmpty: "Write a note first.",
    slotDateTime: "Choose a date and start time.",
    locationTooLong: "Keep the location or link under 300 characters.",
    generic: "Something went wrong. Please try again.",
  },
} as const;

// Database error codes this feature maps to messages.
export const pipelineDbErrors: Record<string, string> = {
  not_company_member: pipelineStrings.errors.not_company_member,
  application_withdrawn: pipelineStrings.errors.application_withdrawn,
  invalid_status: pipelineStrings.errors.invalid_status,
  slot_in_past: pipelineStrings.errors.slot_in_past,
  application_closed: pipelineStrings.errors.application_closed,
  slot_limit_reached: pipelineStrings.errors.slot_limit_reached,
};
