// User-facing strings for the admin area.
export const adminStrings = {
  title: "Admin",
  intro: "Review verification requests and first job posts. Moderation, places and analytics arrive in a later phase.",
  verification: {
    title: "Verification requests",
    description: "Companies, mentors and buddies waiting to be verified.",
    empty: "No requests are waiting.",
    kind: { company: "Company", mentor: "Mentor", buddy: "Settle-In Buddy", flat_lister_id: "Flat lister ID" },
    requestedBy: "Requested by",
    note: "Note from the applicant",
    noNote: "No note given.",
    viewCompany: "Open company page",
    mentorProfile: "Mentor profile",
    noMentorProfile: "No mentor profile yet.",
    mentorYears: (years: number) => `${years} ${years === 1 ? "year" : "years"} of experience`,
    mentorIndustries: "Industries",
    mentorSessionTypes: "Session types",
  },
  jobs: {
    title: "Jobs waiting for review",
    description: "A company's first job is reviewed before it goes live.",
    empty: "No jobs are waiting.",
    sendBack: "Send back to draft",
  },
  approve: "Approve",
  reject: "Reject",
  reasonLabel: "Reason (shown to the applicant)",
  reasonOptional: "Reason (optional, kept in the audit log)",
  reasonRequired: "Give a reason of at least 5 characters.",
  confirm: "Confirm",
  cancel: "Cancel",
  working: "Saving…",
  done: "Saved.",
  waiting: (count: number) => `${count} waiting`,
  errors: {
    admin_only: "Only admins can do this.",
    request_not_found: "That request no longer exists.",
    request_already_decided: "Someone already decided this request.",
    reason_required: "A reason is required when rejecting.",
    job_not_pending_review: "That job is no longer waiting for review.",
    company_not_verified: "The company must be verified before its job can go live.",
    generic: "Could not save. Please try again.",
  },
} as const;
