// User-facing strings for sign-in (kept in one place for later Urdu/Hindi translation).
export const authStrings = {
  title: "Log in to NextStep",
  subtitle: "Welcome back.",
  signUpTitle: "Create your NextStep account",
  signUpSubtitle: "It's free. You'll confirm your email, then tell us a little about yourself.",
  modeSwitch: "Log in or sign up",
  logInButton: "Log in",
  signUpButton: "Sign up",
  forgotPassword: "Forgot password?",
  emailLinkInstead: "Email me a sign-in link instead",
  backToPassword: "Use my password instead",
  confirmPasswordLabel: "Repeat the password",
  newPasswordHint: "At least 8 characters.",
  createAccount: "Create account",
  creating: "Creating account…",
  checkEmailTitle: "Check your email",
  checkEmailSignUp: (to: string) =>
    `We sent a confirmation link to ${to}. Open it on this device to finish creating your account. It can take a minute; check spam too.`,
  linkSentTitle: "Check your email",
  linkSent: (to: string) => `We sent a sign-in link to ${to}. Open it on this device to log in.`,
  haveCode: "Got a 6-digit code instead?",
  forgotTitle: "Reset your password",
  forgotSubtitle: "Enter your email and we'll send you a link to set a new password.",
  sendResetLink: "Send reset link",
  resetSent: (to: string) =>
    `If an account exists for ${to}, we sent a link to set a new password. Open it on this device.`,
  backToLogIn: "Back to log in",
  resetTitle: "Set a new password",
  resetSubtitle: "Choose a new password for your account.",
  resetDone: "Password updated. You're logged in.",
  phoneTab: "Phone",
  emailTab: "Email code",
  passwordTab: "Password",
  passwordLabel: "Password",
  passwordHint: "Use the password you set in Settings → Password.",
  signInWithPassword: "Log in",
  signingIn: "Logging in…",
  noPasswordYet: "Signed up with an email link and never set a password? Use “Forgot password?” to create one.",
  phoneLabel: "Mobile number",
  phoneHint: "Indian mobile number. We'll text you a 6-digit code.",
  emailLabel: "Email address",
  emailHint: "We'll email you a link that logs you in.",
  sendCode: "Send code",
  sendLink: "Email me a link",
  sending: "Sending…",
  codeLabel: "Enter the 6-digit code",
  codeSentTo: (to: string) => `Code sent to ${to}`,
  verify: "Verify and continue",
  verifying: "Verifying…",
  changeContact: "Use a different number or email",
  resend: "Resend code",
  emailLinkHint: "You can also tap the link in the email on this device.",
  orContinueWith: "or",
  google: "Continue with Google",
  errors: {
    invalidPhone: "Enter a valid 10-digit Indian mobile number.",
    invalidEmail: "Enter a valid email address.",
    invalidCode: "Enter the 6-digit code.",
    wrongCode: "That code is wrong or has expired. Try again or resend.",
    rateLimited: "Too many attempts. Please wait a minute and try again.",
    emailLimit:
      "We can't send more emails right now because the hourly email limit was reached. Please try again in about an hour. If you already have a password, you can log in with it now.",
    providerDisabled: "This sign-in method isn't set up yet. Try another option.",
    generic: "Something went wrong. Please try again.",
    callbackFailed: "That sign-in link is invalid or has expired. Please sign in again.",
    oauthFailed: "Google sign-in isn't available right now. Try email instead.",
    wrongPassword: "That email and password don't match. Check them, or use “Forgot password?”.",
    emailNotConfirmed: "Please confirm your email first: open the link we emailed you when you signed up.",
    passwordRequired: "Enter your password.",
  },
} as const;

// Settings → Password.
export const passwordStrings = {
  pageTitle: "Password",
  intro: "Set a password so you can also sign in with your email and password. Email codes keep working.",
  newLabel: "New password",
  newHint: "At least 8 characters. Avoid passwords you use on other sites.",
  confirmLabel: "Repeat the password",
  save: "Save password",
  saving: "Saving…",
  saved: "Password saved. You can now sign in with your email and password.",
  needsEmail: "Password sign-in needs an email address on your account. Your account uses a phone number, so keep signing in with a code.",
  settingsCard: "Password",
  settingsCardBody: "Set or change the password for email sign-in.",
  errors: {
    tooShort: "Use at least 8 characters.",
    tooLong: "Use at most 72 characters.",
    mismatch: "The two passwords don't match.",
    weak: "That password is too weak or appears in known data leaks. Choose a different one.",
    same: "That's already your password.",
    reauth: "For your security, sign out, sign in again with an email code, then set the password.",
    signedOut: "Your session has ended. Please sign in again.",
    generic: "Could not save the password. Please try again.",
  },
} as const;
