// User-facing strings for sign-in (kept in one place for later Urdu/Hindi translation).
export const authStrings = {
  title: "Sign in to NextStep",
  subtitle: "New here? Signing in creates your account.",
  phoneTab: "Phone",
  emailTab: "Email",
  phoneLabel: "Mobile number",
  phoneHint: "Indian mobile number. We'll text you a 6-digit code.",
  emailLabel: "Email address",
  emailHint: "We'll email you a sign-in link and a 6-digit code.",
  sendCode: "Send code",
  sending: "Sending…",
  codeLabel: "Enter the 6-digit code",
  codeSentTo: (to: string) => `Code sent to ${to}`,
  verify: "Verify and continue",
  verifying: "Verifying…",
  changeContact: "Use a different number or email",
  resend: "Resend code",
  emailLinkHint: "You can also tap the link in the email on this device.",
  orContinueWith: "or",
  google: "Continue with Google",
  errors: {
    invalidPhone: "Enter a valid 10-digit Indian mobile number.",
    invalidEmail: "Enter a valid email address.",
    invalidCode: "Enter the 6-digit code.",
    wrongCode: "That code is wrong or has expired. Try again or resend.",
    rateLimited: "Too many attempts. Please wait a minute and try again.",
    providerDisabled: "This sign-in method isn't set up yet. Try another option.",
    generic: "Something went wrong. Please try again.",
    callbackFailed: "That sign-in link is invalid or has expired. Please sign in again.",
    oauthFailed: "Google sign-in isn't available right now. Try phone or email.",
  },
} as const;
