// User-facing strings for sign-in (kept in one place for later Urdu/Hindi translation).
export const authStrings = {
  title: "Sign in to NextStep",
  subtitle: "New here? Signing in creates your account.",
  phoneTab: "Phone",
  emailTab: "Email code",
  passwordTab: "Password",
  passwordLabel: "Password",
  passwordHint: "Use the password you set in Settings → Password.",
  signInWithPassword: "Sign in",
  signingIn: "Signing in…",
  noPasswordYet: "No password yet? Sign in with an email code once, then set one in Settings → Password.",
  phoneLabel: "Mobile number",
  phoneHint: "Indian mobile number. We'll text you a 6-digit code.",
  emailLabel: "Email address",
  emailHint: "We'll email you a sign-in link and a 6-digit code.",
  sendCode: "Send code",
  sending: "Sending…",
  codeLabel: "Enter the 6-digit code",
  codeSentTo: (to: string) => `Code sent to ${to}`,
  verify: "Verify and continue",
  verifying: "Verifying…",
  changeContact: "Use a different number or email",
  resend: "Resend code",
  emailLinkHint: "You can also tap the link in the email on this device.",
  orContinueWith: "or",
  google: "Continue with Google",
  errors: {
    invalidPhone: "Enter a valid 10-digit Indian mobile number.",
    invalidEmail: "Enter a valid email address.",
    invalidCode: "Enter the 6-digit code.",
    wrongCode: "That code is wrong or has expired. Try again or resend.",
    rateLimited: "Too many attempts. Please wait a minute and try again.",
    providerDisabled: "This sign-in method isn't set up yet. Try another option.",
    generic: "Something went wrong. Please try again.",
    callbackFailed: "That sign-in link is invalid or has expired. Please sign in again.",
    oauthFailed: "Google sign-in isn't available right now. Try email instead.",
    wrongPassword: "That email and password don't match. Check them, or sign in with an email code.",
    emailNotConfirmed: "Confirm your email first: sign in once with an email code.",
    passwordRequired: "Enter your password.",
  },
} as const;

// Settings → Password.
export const passwordStrings = {
  pageTitle: "Password",
  intro: "Set a password so you can also sign in with your email and password. Email codes keep working.",
  newLabel: "New password",
  newHint: "At least 8 characters. Avoid passwords you use on other sites.",
  confirmLabel: "Repeat the password",
  save: "Save password",
  saving: "Saving…",
  saved: "Password saved. You can now sign in with your email and password.",
  needsEmail: "Password sign-in needs an email address on your account. Your account uses a phone number, so keep signing in with a code.",
  settingsCard: "Password",
  settingsCardBody: "Set or change the password for email sign-in.",
  errors: {
    tooShort: "Use at least 8 characters.",
    tooLong: "Use at most 72 characters.",
    mismatch: "The two passwords don't match.",
    weak: "That password is too weak or appears in known data leaks. Choose a different one.",
    same: "That's already your password.",
    reauth: "For your security, sign out, sign in again with an email code, then set the password.",
    signedOut: "Your session has ended. Please sign in again.",
    generic: "Could not save the password. Please try again.",
  },
} as const;
