// User-facing strings for notifications (one place, for later translation).
export const notificationStrings = {
  title: "Notifications",
  loading: "Loading your notifications",
  bellLabel: (count: number) =>
    count === 0 ? "Notifications" : count === 1 ? "Notifications, 1 unread" : `Notifications, ${count} unread`,
  unread: "Unread",
  markAllRead: "Mark all as read",
  marking: "Marking…",
  allRead: "All caught up.",
  remove: "Delete notification",
  removed: "Notification deleted.",
  loadMore: "Load more",
  loadingMore: "Loading…",
  settingsLink: "Notification settings",
  emptyTitle: "No notifications yet",
  emptyBody: "Updates about your applications, sessions, requests and messages will show up here.",
  settings: {
    title: "Notification settings",
    pageTitle: "Settings",
    pageIntro: "Manage how NextStep keeps you informed.",
    notificationsCard: "Notifications",
    notificationsCardBody: "Choose which updates reach you by email.",
    loading: "Loading your settings",
    intro: "You always get notifications inside NextStep. Choose which ones should also reach you by email.",
    emailHeading: "Email",
    emailEnabled: "Email notifications",
    emailEnabledHint: "Turn off to stop all notification emails.",
    emailNeedsAddress: "Emails go to the address on your account. If you signed up with a phone number only, no emails are sent.",
    typesHeading: "Email me when",
    whatsappHeading: "WhatsApp",
    whatsappOptIn: "WhatsApp updates",
    whatsappHint: "WhatsApp messages are not sent yet. If you opt in now, we will use it once this is available.",
    save: "Save settings",
    saving: "Saving…",
    saved: "Settings saved.",
    back: "All notifications",
  },
  errors: {
    signedOut: "Please sign in first.",
    invalid: "Please check your choices and try again.",
    generic: "Something went wrong. Please try again.",
  },
} as const;
