// User-facing strings for the mentee side of mentorship (find a mentor, book, my sessions).
import { MENTORSHIP_ERRORS, MENTORSHIP_GENERIC_ERROR } from "../labels";

export const bookingStrings = {
  cancel: "Cancel",
  back: "Back to mentors",
  backToSessions: "Back to my sessions",
  list: {
    pageTitle: "Find a mentor",
    intro: "Book a session with a verified mentor for career guidance, a CV review or a mock interview.",
    mySessions: "My sessions",
    filtersHeading: "Filter mentors",
    city: "City",
    anyCity: "Any city",
    sessionType: "Session type",
    anySessionType: "Any session type",
    skill: "Expertise",
    anySkill: "Any expertise",
    apply: "Show mentors",
    clear: "Clear filters",
    emptyTitle: "No mentors match yet",
    emptyBody: "Try fewer filters, or check back soon as more mentors are verified.",
    count: (count: number) => (count === 1 ? "1 mentor" : `${count} mentors`),
    view: "View profile",
  },
  mentor: {
    years: (years: number) => (years === 1 ? "1 year of experience" : `${years} years of experience`),
    newMentor: "New mentor",
    rating: (avg: number, count: number) => `${avg.toFixed(1)} (${count})`,
    ratingLabel: (avg: number, count: number) =>
      `Rated ${avg.toFixed(1)} out of 5 from ${count} ${count === 1 ? "session" : "sessions"}`,
    about: "About",
    noBio: "This mentor has not written a bio yet.",
    industries: "Industries",
    skills: "Expertise",
    languages: "Languages",
    offers: "Sessions offered",
    sessionLength: (minutes: number) => `${minutes}-minute sessions`,
    timezone: (zone: string) => `Mentor's time zone: ${zone}`,
    unnamed: "Mentor",
    notFoundTitle: "Mentor not found",
    notFoundBody: "This mentor is not available, or the link is wrong.",
  },
  booking: {
    heading: "Book a session",
    stepType: "1. What would you like help with?",
    stepSlot: "2. Pick a time",
    stepNote: "3. Your goal for the session (optional)",
    notePlaceholder: "For example: I have an interview next week and want to practise.",
    noteHint: "Up to 1000 characters. The mentor sees this before accepting.",
    timesIn: (zone: string) => `Times are shown in your time zone (${zone}).`,
    loadingSlots: "Loading free times…",
    noSlots: "No free times in these two weeks.",
    noSlotsAtAll: "This mentor has no free times in the next 30 days.",
    earlier: "Earlier",
    later: "Next 2 weeks",
    slotGroupLabel: (day: string) => `Free times on ${day}`,
    chooseType: "Choose a session type.",
    chooseSlot: "Pick a time for your session.",
    selected: (when: string) => `Selected: ${when}`,
    submit: "Request session",
    submitting: "Sending request…",
    sent: "Request sent. The mentor will accept or decline.",
    ownProfile: "This is your own mentor profile. Other members can book you from here.",
    manageProfile: "Open mentor dashboard",
    limitReached: "You already have 2 upcoming sessions. Finish or cancel one before booking another.",
    notAccepting: "This mentor isn't taking bookings right now.",
  },
  sessions: {
    pageTitle: "My sessions",
    intro: "Sessions you have booked with mentors.",
    upcoming: "Upcoming",
    upcomingEmpty: "No upcoming sessions.",
    past: "Past and other sessions",
    pastEmpty: "Nothing here yet.",
    emptyTitle: "You have not booked a session yet",
    emptyBody: "Find a mentor and request a time that suits you.",
    findMentor: "Find a mentor",
    with: (name: string) => `With ${name}`,
    open: "View session",
  },
  detail: {
    pageTitle: "Session",
    when: "When",
    type: "Session type",
    mentor: "Mentor",
    viewMentor: "View mentor profile",
    goal: "Your goal",
    noGoal: "No goal note added.",
    join: "Join meeting",
    joinHint: "The link opens in a new tab.",
    waiting: "The mentor has not answered yet. You will see the meeting link here once they accept.",
    expired: "The mentor did not answer before the start time, so this request expired.",
    declineReason: "Reason given by the mentor",
    cancelReason: "Reason for cancelling",
    cancelledByYou: "You cancelled this session.",
    cancelledByMentor: "The mentor cancelled this session.",
    notFoundTitle: "Session not found",
    notFoundBody: "This session does not exist, or you are not part of it.",
  },
  cancelDialog: {
    button: "Cancel session",
    title: "Cancel this session?",
    body: "The mentor will see that you cancelled. This frees the time for someone else.",
    reason: "Reason (optional)",
    confirm: "Yes, cancel session",
    cancelling: "Cancelling…",
    keep: "Keep session",
    done: "Session cancelled.",
  },
  feedback: {
    heading: "Feedback",
    formHeading: "How was the session?",
    rating: "Your rating",
    ratingOption: (value: number) => `${value} out of 5`,
    comment: "Comment (optional)",
    commentHint: "Up to 1000 characters. The mentor can read this.",
    submit: "Send feedback",
    submitting: "Sending…",
    sent: "Thank you for your feedback.",
    yours: "Your feedback",
    mentors: "From your mentor",
    ratingGiven: (value: number) => `${value} out of 5`,
    nextSteps: "Recommended next steps",
    none: "No feedback yet.",
  },
  errors: {
    invalid: "Please check the form and try again.",
    notSignedIn: "Please sign in first.",
    type: "Choose a session type.",
    slot: "Pick a time for your session.",
    note: "Your note is too long (1000 characters at most).",
    reason: "The reason is too long (500 characters at most).",
    rating: "Please choose a rating from 1 to 5.",
    comment: "Your comment is too long (1000 characters at most).",
    slots: "Could not load free times. Please try again.",
    generic: MENTORSHIP_GENERIC_ERROR,
    db: MENTORSHIP_ERRORS,
  },
} as const;
