// User-facing strings for the Settle-In Buddy dashboard (one place, for later translation).

export const buddyStrings = {
  title: "Buddy dashboard",
  intro: "Help community members who are moving to your city. Their phone number and email are never shown; you chat in the app once they accept your offer.",
  create: {
    title: "Become a Settle-In Buddy",
    body: "Tell newcomers how you can help. An admin verifies every buddy before requests are shown.",
  },
  profile: {
    title: "My buddy profile",
    city: "Your city",
    cityPlaceholder: "Choose a city",
    neighbourhoods: "Neighbourhoods you know well (optional)",
    noNeighbourhoods: "Choose a city to see its neighbourhoods.",
    bio: "About you (optional)",
    bioHint: "How long you've lived here and how you can help. Up to 1,000 characters.",
    languages: "Languages you speak (optional)",
    languagesHint: "Separate with commas, e.g. Urdu, Hindi, English.",
    helpTypes: "What can you help with?",
    active: "Show me requests and let newcomers see me",
    activeHint: "Turn this off to take a break.",
    submitCreate: "Create buddy profile",
    save: "Save profile",
    saving: "Saving…",
    saved: "Profile saved.",
    rating: (avg: string, count: number) => `${avg} ★ from ${count} ${count === 1 ? "rating" : "ratings"}`,
  },
  verification: {
    pendingTitle: "Waiting for verification",
    pendingBody: "An admin is reviewing your buddy profile. You'll see relocation requests once you're approved.",
    approvedTitle: "Verified buddy",
    approvedBody: "You can see open requests in your city and offer help.",
    rejectedTitle: "Verification was not approved",
    rejectedReason: (reason: string) => `Reason: ${reason}`,
    reRequest: "Ask for another review",
    noteLabel: "Note for the admin (optional)",
    send: "Send request",
    sending: "Sending…",
    sent: "Sent for review.",
    cancel: "Cancel",
    paused: "Your profile is paused, so you won't see new requests.",
  },
  requests: {
    title: "Open requests in your city",
    emptyTitle: "No open requests right now",
    emptyBody: "When someone is moving to your city and needs help, their request appears here.",
    notVerified: "Requests appear here once your profile is verified.",
    moving: (date: string) => `Moving ${date}`,
    movingRange: (from: string, to: string) => `Moving between ${from} and ${to}`,
    offer: "Offer help",
    offerTitle: (name: string) => `Offer to help ${name}`,
    offerBody: "They'll see your profile and message. If they accept, a chat opens.",
    message: "Message (optional)",
    messageHint: "Say how you can help. Don't include your phone number.",
    send: "Send offer",
    sending: "Sending…",
    sent: "Offer sent.",
    cancel: "Cancel",
    reportLabel: "Report request",
    someone: "A community member",
  },
  offers: {
    title: "My offers",
    empty: "You haven't offered help yet.",
    to: (name: string, city: string) => `${name} · moving to ${city}`,
    withdraw: "Withdraw offer",
    withdrawing: "Withdrawing…",
    withdrawn: "Offer withdrawn.",
    openChat: "Open chat",
    requestClosed: "This request is closed.",
  },
  errors: {
    city: "Choose your city.",
    bio: "Keep this under 1,000 characters.",
    languages: "List up to 10 languages.",
    helpTypes: "Choose at least one way you can help.",
    message: "Keep the message under 1,000 characters.",
    note: "Keep the note under 1,000 characters.",
    invalid: "Some details are missing or invalid. Please check the form.",
    generic: "Something went wrong. Please try again.",
    not_authenticated: "Please sign in again.",
    onboarding_required: "Finish setting up your profile first.",
    profile_exists: "You already have a buddy profile.",
    message_too_long: "Keep the message under 1,000 characters.",
    request_not_available: "This request is no longer open to you.",
    already_offered: "You've already offered help on this request.",
    offer_not_found: "That offer can no longer be withdrawn.",
    not_rejected: "A review is already in progress.",
    note_too_long: "Keep the note under 1,000 characters.",
  },
} as const;
