// User-facing strings for the employer area (kept in one place for later Urdu/Hindi translation).
export const employerStrings = {
  dashboard: {
    title: "Employer dashboard",
    subtitle: "Manage your company, post jobs and review applicants.",
    registerCompany: "Register your company",
    registerAnother: "Register another company",
    emptyTitle: "You haven't registered a company yet",
    emptyBody: "Register your company to post jobs. An admin verifies each company before its jobs go live.",
    editCompany: "Edit company",
    postJob: "Post a job",
    jobsTitle: "Jobs",
    noJobs: "No jobs yet. Post your first job to start receiving applications.",
    applicants: (n: number) => (n === 1 ? "1 applicant" : `${n} applicants`),
    deadline: (date: string) => `Apply by ${date}`,
    noDeadline: "No deadline",
    viewApplicants: "View applicants",
    pendingHelp: "You can draft jobs now. They can be published once an admin verifies your company.",
    approvedHelp: "Your company is verified. Your first job is reviewed by an admin; later jobs go live straight away.",
    rejectedHelp: "Verification was declined, so jobs can't be published yet.",
    rejectionReason: (reason: string) => `Reason given: ${reason}`,
    hidden: "This company is hidden by an admin and is not visible to the public.",
  },
  verification: {
    requestAgain: "Request verification again",
    dialogTitle: "Request verification again",
    dialogBody: "Tell the admin what has changed since the last review.",
    noteLabel: "Note for the admin (optional)",
    submit: "Send request",
    sending: "Sending…",
    sent: "Verification requested. An admin will review your company.",
    cancel: "Cancel",
  },
  affiliations: {
    title: "People who say they work here",
    help: "Confirm colleagues so the referrals they make show as coming from a confirmed employee.",
    empty: "Nobody has said they work here yet.",
    confirm: "Confirm",
    unconfirm: "Remove confirmation",
    confirmed: "Confirmed",
    unconfirmed: "Not confirmed",
    unknownPerson: "Community member",
    saved: "Saved.",
  },
  jobActions: {
    edit: "Edit",
    publish: "Publish",
    republish: "Reopen",
    withdraw: "Withdraw from review",
    close: "Close job",
    delete: "Delete",
    deleteTitle: "Delete this draft?",
    deleteBody: "The draft is removed for good. This can't be undone.",
    deleteConfirm: "Delete draft",
    cancel: "Cancel",
    working: "Working…",
    published: "Your job is live.",
    sentForReview: "Your first job is reviewed by an admin before it goes live.",
    withdrawn: "The job is back in your drafts.",
    closed: "The job is closed and no longer accepts applications.",
    deleted: "Draft deleted.",
  },
  company: {
    newTitle: "Register your company",
    newSubtitle: "An admin checks every company before its jobs can go live.",
    editTitle: "Edit company",
    name: "Company name",
    industry: "Industry",
    industryPlaceholder: "e.g. Software, Logistics, Healthcare",
    size: "Company size",
    sizePlaceholder: "Choose a size",
    website: "Website",
    websiteHint: "Starts with https://",
    description: "About the company",
    communityOwned: "This is a community-owned business",
    leapFriendly: "We welcome LEAP graduates",
    leapFriendlyHint: "Your jobs appear under the LEAP-friendly filter.",
    verificationNote: "Note for the admin (optional)",
    verificationNoteHint: "Anything that helps verify the company: registration number, your role, a contact at the company.",
    create: "Register company",
    save: "Save changes",
    saving: "Saving…",
    saved: "Company details saved.",
    backToDashboard: "Back to employer dashboard",
  },
  logo: {
    title: "Logo",
    hint: "JPEG, PNG or WebP, up to 2 MB.",
    choose: "Upload a logo",
    replace: "Replace logo",
    uploading: "Uploading…",
    saved: "Logo updated.",
    wrongType: "Choose a JPEG, PNG or WebP image.",
    tooLarge: "The image is larger than 2 MB.",
    failed: "Could not upload the logo. Please try again.",
    alt: (name: string) => `${name} logo`,
  },
  locations: {
    title: "Locations",
    empty: "No locations added yet.",
    city: "City",
    cityPlaceholder: "Choose a city",
    address: "Address (optional)",
    add: "Add location",
    adding: "Adding…",
    remove: "Remove",
    removeLabel: (place: string) => `Remove location ${place}`,
    limit: "You can add up to 10 locations.",
  },
  job: {
    newTitle: "Post a job",
    editTitle: "Edit job",
    forCompany: (name: string) => `For ${name}`,
    title: "Job title",
    description: "Job description",
    descriptionHint: "What the person will do day to day. Plain text.",
    requirements: "Requirements (optional)",
    requirementsHint: "Skills, experience or qualifications you are looking for.",
    jobType: "Job type",
    workMode: "Work mode",
    level: "Experience level",
    choose: "Choose…",
    city: "City",
    cityRemoteHint: "Optional for remote jobs.",
    neighbourhood: "Neighbourhood (optional)",
    neighbourhoodPlaceholder: "Any / not sure",
    noNeighbourhood: "Any / not sure",
    address: "Address (optional)",
    locationNote: "Shown on the job page. Without a map pin, the job is placed at the neighbourhood or city you choose.",
    pinTitle: "Map pin (optional)",
    pinLabel: "Place the workplace on the map",
    pinHint: "Helps seekers search by distance. Changing the city or neighbourhood clears the pin.",
    openings: "Number of openings",
    deadline: "Application deadline (optional)",
    skills: "Skills (up to 10)",
    salaryTitle: "Salary",
    salaryMin: "Minimum (lakh per year)",
    salaryMax: "Maximum (lakh per year)",
    salaryHint: "Leave both empty if you'd rather not say. Example: 8 and 12 for ₹8–12 lakh a year.",
    salaryVisible: "Show salary on the job post",
    salaryHiddenHint: "When off, the salary is saved but nobody outside your company can see it.",
    questionsTitle: "Screening questions (optional)",
    questionsHint: "Up to 10 short questions applicants answer when they apply.",
    questionLabel: (n: number) => `Question ${n}`,
    questionRequired: "Applicants must answer",
    addQuestion: "Add a question",
    removeQuestion: (n: number) => `Remove question ${n}`,
    questionsLocked: "This job already has applications, so the screening questions can no longer be changed.",
    saveDraft: "Save draft",
    save: "Save changes",
    saveAndPublish: "Save and publish",
    saving: "Saving…",
    savedDraft: "Job saved.",
    cannotPublishHint: "Publishing is available once an admin verifies your company.",
  },
  // Messages for error codes raised by database functions and triggers.
  dbErrors: {
    invalid_company_name: "Enter a company name between 2 and 120 characters.",
    company_limit_reached: "You can register up to 3 companies.",
    onboarding_required: "Finish setting up your profile first.",
    not_company_owner: "Only the company owner can do that.",
    verification_not_rejected: "Verification can only be requested again after it was declined.",
    not_company_member: "You are not a member of this company.",
    company_not_verified: "Your company needs to be verified by an admin before jobs can be published.",
    job_awaiting_review: "This job is waiting for an admin to review it.",
    invalid_job_status_change: "That change isn't possible for this job right now.",
    job_must_start_as_draft: "New jobs start as drafts.",
  },
  errors: {
    generic: "Something went wrong. Please try again.",
    notSignedIn: "Please sign in again.",
    notFound: "We couldn't find that, or you don't have access to it.",
    deleteOnlyDrafts: "Only drafts can be deleted. Close the job instead.",
    locationLimit: "You can add up to 10 locations.",
    name: "Enter a company name between 2 and 120 characters.",
    website: "Enter a full web address starting with https://",
    tooLong: (max: number) => `Keep this under ${max} characters.`,
    jobTitle: "Enter a job title between 3 and 140 characters.",
    jobDescription: "Describe the job (up to 8,000 characters).",
    choose: "Choose an option.",
    cityRequired: "Choose a city (only remote jobs can skip this).",
    openings: "Enter a whole number between 1 and 1,000.",
    deadlinePast: "The deadline can't be in the past.",
    salaryNumber: "Enter an amount in lakh, like 8 or 8.5.",
    salaryOrder: "The maximum can't be lower than the minimum.",
    question: "Write a question between 3 and 300 characters.",
    tooManySkills: "Choose up to 10 skills.",
    tooManyQuestions: "Add up to 10 questions.",
  },
} as const;
