// User-facing strings for flats & rooms (PRODUCT_SPEC §7.3). Kept in one place so they can be translated later.
export const flatsStrings = {
  search: {
    title: "Flats & rooms",
    subtitle: "Homes listed by community members. Exact addresses are shared only after the lister accepts your request.",
    filters: "Filters",
    city: "City",
    anyCity: "Any city",
    neighbourhood: "Neighbourhood",
    anyNeighbourhood: "Any neighbourhood",
    rentMin: "Minimum rent (₹ a month)",
    rentMax: "Maximum rent (₹ a month)",
    listingType: "Type",
    furnishing: "Furnishing",
    anyFurnishing: "Any furnishing",
    apply: "Show flats",
    clear: "Clear filters",
    results: (count: number) => (count === 1 ? "1 flat or room" : `${count} flats and rooms`),
    emptyTitle: "No flats found",
    emptyBody: "Try removing a filter or searching another area.",
    emptyNoFilters: "Nobody has listed a flat yet. Check back soon, or list yours.",
    listYours: "List a flat or room",
    myListings: "My listings",
    pagination: "Pages",
    previous: "Previous",
    next: "Next",
    pageOf: (page: number, pages: number) => `Page ${page} of ${pages}`,
    loading: "Loading flats",
  },
  card: {
    photoAlt: (title: string) => `Photo of ${title}`,
    availableFrom: (date: string) => `Available from ${date}`,
    beds: (count: number) => (count === 1 ? "1 bedroom" : `${count} bedrooms`),
    baths: (count: number) => (count === 1 ? "1 bathroom" : `${count} bathrooms`),
  },
  detail: {
    notFoundTitle: "Listing not found",
    notFoundBody: "This listing was removed, is no longer available, or is not open to you.",
    back: "Back to flats",
    photos: "Photos",
    noPhotos: "No photos yet",
    photoAlt: (title: string, index: number) => `Photo ${index} of ${title}`,
    about: "About this place",
    details: "Details",
    deposit: "Deposit",
    furnishing: "Furnishing",
    availableFrom: "Available from",
    minStay: "Minimum stay",
    months: (count: number) => (count === 1 ? "1 month" : `${count} months`),
    noMinStay: "No minimum",
    bedrooms: "Bedrooms",
    bathrooms: "Bathrooms",
    food: "Food in the home",
    tenants: "Open to",
    amenities: "Amenities",
    listedBy: "Listed by",
    areaTitle: "Approximate area",
    areaBody:
      "For the lister's safety, only the area is shown. The exact address is shared with you after the lister accepts your contact request.",
    addressTitle: "Exact address",
    mapApprox: "Approximate location of the flat (within about 500 m)",
    mapApproxNote: "The pin shows the approximate area, not the exact building.",
    mapExact: "Exact location of the flat",
    addressShared: "The lister accepted your request, so the address is shared with you. Please keep it private.",
    addressOwn: "Only you and people whose request you accept can see this.",
    landmark: "Landmark",
    manage: "Edit or manage this listing",
    ownListing: "This is your listing.",
    statusNote: {
      paused: "This listing is paused and is not shown in search.",
      rented: "This place has been rented.",
      expired: "This listing has expired.",
      active: "",
    },
  },
  contact: {
    title: "Contact the lister",
    intro: "Introduce yourself",
    introHint: "Say who you are, when you are moving and why this place suits you. Phone numbers are never shown; you will chat in the app.",
    introPlaceholder: "Assalamu alaikum, I'm moving to the city for a new job…",
    send: "Send request",
    sending: "Sending…",
    sent: "Request sent. You'll be able to chat once the lister accepts.",
    pending: "Your request is waiting for the lister's reply.",
    accepted: "The lister accepted your request.",
    declined: "The lister declined your earlier request. You can send a new one.",
    withdrawn: "You withdrew your earlier request. You can send a new one.",
    openChat: "Open chat",
    withdraw: "Withdraw request",
    withdrawing: "Withdrawing…",
    withdrawnToast: "Request withdrawn.",
    withdrawQuestion: "Withdraw your request?",
    withdrawBody: "You will lose access to the exact address.",
    cancel: "Cancel",
  },
  form: {
    newTitle: "List a flat or room",
    newIntro: "Step 1 of 3: describe the place. Next you'll add the address and photos, then publish.",
    editTitle: "Edit listing",
    listingType: "What are you listing?",
    city: "City",
    cityPlaceholder: "Choose a city",
    neighbourhood: "Neighbourhood",
    neighbourhoodPlaceholder: "Choose a neighbourhood",
    neighbourhoodNone: "Not listed / not sure",
    title: "Title",
    titlePlaceholder: "e.g. Furnished room near Kurla station",
    description: "Description",
    descriptionHint: "Plain text. Don't put a phone number or the exact address here.",
    rent: "Rent (₹ a month)",
    deposit: "Deposit (₹)",
    depositHint: "Leave empty if there is none.",
    furnishing: "Furnishing",
    availableFrom: "Available from",
    minStay: "Minimum stay (months)",
    bedrooms: "Bedrooms",
    bathrooms: "Bathrooms",
    amenities: "Amenities",
    food: "Food in the home",
    foodNone: "No preference",
    tenants: "Who can rent it?",
    tenantsHint: "People outside this choice will not see the listing at all.",
    create: "Save and continue",
    save: "Save changes",
    saving: "Saving…",
    saved: "Saved.",
  },
  address: {
    title: "Exact address",
    intro:
      "Kept private. Only people whose contact request you accept can see it. Everyone else sees an approximate area.",
    addressLine: "Address",
    addressPlaceholder: "Flat / building, street, area",
    landmark: "Landmark (optional)",
    locationTitle: "Location pin",
    useLocation: "Use my current location",
    locating: "Finding your location…",
    locationSet: "Location set. Save to keep it.",
    pickerLabel: "Place the flat on the map",
    locationHintMap:
      "Tap the map or drag the pin to the flat, or use your current location while you are there. If you skip it, we use the centre of the neighbourhood (or the city) instead, so the approximate area shown to others will be less accurate.",
    locationSaved: "A location pin is saved for this listing.",
    locationHint:
      "Tap this while you are at the flat. If you skip it, we use the centre of the neighbourhood (or the city) instead, so the approximate area shown to others will be less accurate.",
    locationDenied: "We could not read your location. You can still save; the neighbourhood centre will be used.",
    clearLocation: "Undo pin change",
    save: "Save address",
    saving: "Saving…",
    saved: "Address saved.",
    savedArea: "Address saved. The area centre is used as the location because no pin was captured.",
  },
  photos: {
    title: "Photos",
    intro: (max: number) => `Up to ${max} photos. Location data is removed from each photo before it is uploaded.`,
    add: "Add photos",
    uploading: "Uploading…",
    wrongType: "Choose JPEG, PNG or WebP images.",
    tooLarge: "Each photo must be 5 MB or smaller.",
    failed: "Could not upload the photo. Please try again.",
    limit: (max: number) => `A listing can have at most ${max} photos.`,
    remove: (index: number) => `Remove photo ${index}`,
    moveUp: (index: number) => `Move photo ${index} earlier`,
    moveDown: (index: number) => `Move photo ${index} later`,
    alt: (index: number) => `Listing photo ${index}`,
    cover: "Cover",
    empty: "No photos yet. Listings with photos get more replies.",
    removed: "Photo removed.",
    added: "Photo added.",
  },
  manage: {
    title: "My listings",
    intro: "Listings stay live for 30 days. Renew to keep one visible.",
    emptyTitle: "You have no listings",
    emptyBody: "List a flat or a spare room for community members moving to your city.",
    publishTitle: "Publish",
    publishIntro: "Your listing is not visible yet. Add the address, then publish it.",
    needAddress: "Save the address first.",
    publish: "Publish listing",
    view: "View listing",
    edit: "Edit",
    pause: "Pause",
    activate: "Make live",
    rented: "Mark as rented",
    renew: "Renew for 30 days",
    delete: "Delete",
    deleteQuestion: "Delete this listing?",
    deleteBody: "It will be removed from search and pending requests will be declined. This cannot be undone.",
    confirmDelete: "Delete listing",
    cancel: "Cancel",
    working: "Saving…",
    done: "Saved.",
    deleted: "Listing deleted.",
    expiresIn: (days: number) => (days <= 0 ? "Expires today" : days === 1 ? "Expires in 1 day" : `Expires in ${days} days`),
    expiredOn: (date: string) => `Expired on ${date}`,
    requestsTitle: "Contact requests",
    noRequests: "No contact requests yet.",
    accept: "Accept",
    decline: "Decline",
    acceptHint: "Accepting opens a chat and shares the exact address with this person.",
    acceptedToast: "Accepted. A chat is open.",
    declinedToast: "Declined.",
    openChat: "Open chat",
    someone: "A community member",
    back: "Back to my listings",
  },
  requestStatus: { pending: "Pending", accepted: "Accepted", declined: "Declined", withdrawn: "Withdrawn" },
  errors: {
    generic: "Something went wrong. Please try again.",
    notFound: "That listing no longer exists.",
    choose: "Choose an option.",
    title: "Use 5 to 120 characters.",
    tooLong: (max: number) => `Keep this under ${max} characters.`,
    rent: "Enter the monthly rent in rupees.",
    amount: "Enter a valid amount.",
    whole: "Enter a whole number.",
    date: "Choose a date.",
    address: "Enter the address (at least 5 characters).",
    intro: "Write a short introduction (up to 1000 characters).",
    noLocation: "We could not work out a location for this listing. Use your current location and try again.",
  },
  dbErrors: {
    not_authenticated: "Please sign in again.",
    onboarding_required: "Finish setting up your profile first.",
    listing_limit_reached: "You can have at most 10 live listings. Delete or mark one as rented first.",
    invalid_location: "That location is not valid.",
    address_required: "Save the address before publishing.",
    listing_expired: "This listing has expired. Renew it to make it live again.",
    listing_not_found: "That listing no longer exists.",
    invalid_status: "That change is not allowed.",
    invalid_intro: "Write a short introduction (up to 1000 characters).",
    listing_not_available: "This listing is no longer available.",
    own_listing: "This is your own listing.",
    already_requested: "You already have a request for this listing.",
    request_not_found: "That request no longer exists.",
    request_already_decided: "That request was already answered.",
    blocked: "You cannot contact this person.",
    photo_limit_reached: "A listing can have at most 10 photos.",
    invalid_photo_path: "That photo could not be saved.",
    not_lister: "Only the lister can change this listing.",
  },
} as const;
