// User-facing strings for the places directory and place suggestions.
export const placesStrings = {
  title: "Masjids & places",
  subtitle: "Shia masjids, imambargahs, community centres and everyday places, checked by our team.",
  filters: {
    heading: "Filter places",
    search: "Name",
    searchPlaceholder: "e.g. Imambargah",
    city: "City",
    anyCity: "All cities",
    area: "Area",
    anyArea: "All areas",
    type: "Type",
    anyType: "All types",
    apply: "Show places",
    clear: "Clear filters",
  },
  results: (count: number) => (count === 1 ? "1 place" : `${count} places`),
  openMap: "Open the map",
  suggest: "Suggest a place",
  verified: "Verified",
  emptyTitle: "No places found",
  emptyBody: "Try a different city, area or type.",
  emptyNoFilters: "No places have been added yet. Please check back soon.",
  pagination: "Pages of places",
  previous: "Previous",
  next: "Next",
  pageOf: (page: number, pages: number) => `Page ${page} of ${pages}`,
  loading: "Loading places",
  detail: {
    back: "All places",
    address: "Address",
    timings: "Timings",
    contact: "Contact",
    phone: "Phone",
    website: "Website",
    notes: "Good to know",
    photos: "Photos",
    photoAlt: (name: string, n: number) => `Photo ${n} of ${name}`,
    map: "Location",
    mapLabel: (name: string) => `Map showing ${name}`,
    nearby: "Other places nearby",
    nearbyEmpty: "No other places within 2 km yet.",
    away: (distance: string) => `${distance} away`,
    areaGuide: (area: string) => `Area guide for ${area}`,
    correction: "Suggest a correction",
    correctionSignIn: "Sign in to suggest a correction",
    notFoundTitle: "Place not found",
    notFoundBody: "This place may have been removed, or the link is wrong.",
    loading: "Loading place",
  },
  suggestForm: {
    newTitle: "Suggest a place",
    newIntro: "Know a masjid, imambargah or useful place that is missing? Tell us and our team will review it.",
    correctionTitle: "Suggest a correction",
    correctionIntro: (name: string) =>
      `Change whatever is wrong about ${name} and add a short note. Our team will review it before anything changes.`,
    name: "Name",
    type: "Type",
    city: "City",
    chooseCity: "Choose a city",
    area: "Area (optional)",
    noArea: "Not sure / not listed",
    address: "Address (optional)",
    timings: "Timings (optional)",
    timingsHint: "Prayer, majlis or opening times.",
    phone: "Public phone number (optional)",
    phoneHint: "Only the place's own public number, never a private person's.",
    website: "Website (optional)",
    websitePlaceholder: "https://",
    notes: "Anything else people should know (optional)",
    location: "Location on the map (optional)",
    locationSet: "A location is set.",
    locationClear: "Remove the location",
    locationLabel: "Map to choose where the place is",
    note: "Note for our team (optional)",
    noteCorrection: "What is wrong, and how do you know?",
    submit: "Send suggestion",
    submitting: "Sending…",
    sent: "Thank you. Our team will review your suggestion.",
    cancel: "Cancel",
    loading: "Loading the suggestion form",
  },
  mine: {
    heading: "My suggestions",
    empty: "You have not suggested anything yet.",
    newPlace: (name: string) => `New place: ${name}`,
    correctionFor: (name: string) => `Correction for ${name}`,
    correctionRemoved: "Correction for a place that was removed",
    status: { pending: "Waiting for review", approved: "Approved", rejected: "Not accepted" },
    reviewNote: "Reply from our team",
  },
  errors: {
    invalid: "Please check the form and try again.",
    notSignedIn: "Please sign in first.",
    name: "Enter a name of 2 to 150 characters.",
    type: "Choose a type.",
    city: "Choose a city.",
    area: "That area does not belong to the chosen city.",
    address: "The address is too long (300 characters at most).",
    timings: "The timings are too long (1000 characters at most).",
    phone: "Enter a phone number of up to 30 characters (digits, spaces, + and -).",
    website: "Enter a full web address starting with http:// or https://.",
    notes: "The notes are too long (2000 characters at most).",
    note: "The note is too long (1000 characters at most).",
    location: "That location is not valid.",
    placeMissing: "That place no longer exists.",
    generic: "Could not send your suggestion. Please try again.",
    db: {
      onboarding_required: "Finish setting up your profile first.",
      rate_limit_exceeded: "You have sent 10 suggestions today. Please try again tomorrow.",
    } as Record<string, string>,
  },
} as const;
