// User-facing strings for the admin analytics screen.
export const analyticsStrings = {
  title: "Analytics",
  description: "How the platform is doing over a date range. Dates are in India time.",
  from: "From",
  to: "To",
  city: "City",
  allCities: "All cities",
  apply: "Show",
  presets: "Quick ranges",
  preset: (days: number) => `Last ${days} days`,
  range: (from: string, to: string) => `${from} to ${to}`,
  stats: {
    signups: "Sign-ups",
    jobs_posted: "Jobs posted",
    applications: "Applications",
    hires: "Hires",
    mentorship_sessions_booked: "Mentor sessions booked",
    mentorship_sessions_completed: "Mentor sessions completed",
    relocation_requests_opened: "Relocation requests opened",
    relocation_requests_closed: "Relocation requests closed",
    listings_created: "Listings created",
    active_listings: "Active listings now",
    open_reports: "Open reports now",
    pending_verifications: "Pending verifications now",
  },
  byRoleHeading: "New roles in this range",
  byRoleEmpty: "No new roles in this range.",
  byCityHeading: "By city",
  byCityEmpty: "No cities yet.",
  columns: {
    city: "City",
    signups: "Sign-ups",
    jobs: "Jobs posted",
    applications: "Applications",
    relocation: "Relocation requests",
    listings: "Active listings",
  },
  errors: {
    admin_only: "Only admins can see analytics.",
    invalid_range: "The end date must be on or after the start date.",
    generic: "Could not load analytics. Please try again.",
  },
} as const;
