// User-facing strings for job search, job detail, company pages and saved items (one place, for later translation).
export const searchStrings = {
  title: "Find jobs",
  subtitle: "Jobs from verified employers.",
  keywordLabel: "Keyword",
  keywordPlaceholder: "Job title, skill or company",
  search: "Search",
  filters: "Filters",
  filtersWithCount: (count: number) => (count > 0 ? `Filters (${count})` : "Filters"),
  showFilters: "Show filters",
  hideFilters: "Hide filters",
  applyFilters: "Apply filters",
  clear: "Clear all",
  city: "City",
  anyCity: "Any city",
  jobType: "Job type",
  workMode: "Work mode",
  level: "Experience level",
  minSalary: "Minimum salary (lakh a year)",
  minSalaryHint: "Only jobs that show their salary are matched.",
  posted: "Posted",
  postedAny: "Any time",
  postedOptions: { 1: "Last 24 hours", 7: "Last 7 days", 30: "Last 30 days" } as Record<number, string>,
  leapOnly: "LEAP-friendly employers only",
  nearMe: {
    legend: "Distance",
    use: "Use my location",
    locating: "Finding your location…",
    active: "Showing jobs near you",
    radius: "Within",
    km: (km: number) => `${km} km`,
    remove: "Stop using my location",
    denied: "Location permission was denied. Allow it in your browser settings, or filter by city instead.",
    unavailable: "We couldn't get your location. Try again, or filter by city instead.",
    unsupported: "Your browser doesn't support location. Filter by city instead.",
  },
  results: (total: number) => (total === 1 ? "1 job found" : `${total} jobs found`),
  emptyTitle: "No jobs match your search",
  emptyBody: "Try fewer filters or a different keyword.",
  emptyNoFilters: "No jobs are open right now. Please check back soon.",
  previous: "Previous",
  next: "Next",
  pageOf: (page: number, pages: number) => `Page ${page} of ${pages}`,
  pagination: "Search result pages",
  save: {
    save: "Save job",
    saved: "Saved",
    unsave: "Remove from saved jobs",
    failed: "Could not update your saved jobs. Please try again.",
  },
  saveSearch: {
    open: "Save this search",
    title: "Save this search",
    description: "Find it again under Saved jobs & searches.",
    nameLabel: "Name",
    namePlaceholder: "e.g. React jobs in Mumbai",
    alertLabel: "Daily email alert",
    alertHint: "Alerts will be emailed once notifications are switched on.",
    submit: "Save search",
    saving: "Saving…",
    cancel: "Cancel",
    done: "Search saved",
    nameRequired: "Give this search a name (up to 80 characters).",
    limit: "You can keep up to 20 saved searches. Delete one first.",
    failed: "Could not save the search. Please try again.",
  },
  detail: {
    closed: "This job is closed and no longer accepts applications.",
    apply: "Apply now",
    signInToApply: "Sign in to apply",
    applied: "You applied",
    viewApplication: "View application",
    refer: "Refer someone",
    referHint: "Work here? Refer someone you know.",
    relocate: "Relocating for this job? Get help settling in",
    description: "About the job",
    requirements: "Requirements",
    skills: "Skills",
    location: "Location",
    mapNote: "A map view will be added with the maps module.",
    remote: "Remote",
    openings: (n: number) => (n === 1 ? "1 opening" : `${n} openings`),
    deadline: (date: string) => `Apply by ${date}`,
    posted: (when: string) => `Posted ${when}`,
    questions: (n: number) =>
      n === 1 ? "The employer asks 1 screening question when you apply." : `The employer asks ${n} screening questions when you apply.`,
    aboutCompany: "About the company",
    salaryHidden: "Salary not shown",
    notFoundTitle: "Job not found",
    notFoundBody: "This job may have closed or the link is wrong.",
    backToSearch: "Back to job search",
  },
  company: {
    verified: "Verified employer",
    community: "Community business",
    leap: "LEAP-friendly",
    website: "Website",
    locations: "Locations",
    openJobs: "Open jobs",
    noJobs: "This company has no open jobs right now.",
    about: "About",
  },
  saved: {
    title: "Saved jobs & searches",
    jobsTab: "Saved jobs",
    searchesTab: "Saved searches",
    noJobsTitle: "No saved jobs yet",
    noJobsBody: "Tap the bookmark on a job to keep it here.",
    noSearchesTitle: "No saved searches yet",
    noSearchesBody: "Run a search and choose “Save this search”.",
    browse: "Find jobs",
    notOpen: "This job is no longer open.",
    unavailable: "A job you saved is no longer available.",
    remove: "Remove",
    run: "Run search",
    delete: "Delete",
    deleting: "Deleting…",
    alert: "Daily email alert",
    allJobs: "All jobs",
    actionFailed: "Something went wrong. Please try again.",
  },
  recommended: {
    title: "Recommended for you",
    empty: "Add skills to get recommendations",
    emptyBody: "We match open jobs to your skills, preferred cities and experience.",
    cta: "Update my job profile",
  },
} as const;
