// User-facing strings for flatmate matching (kept in one place for later Urdu/Hindi translation).
export const flatmateStrings = {
  pageTitle: "Flatmates",
  pageIntro: "Find someone compatible to share a flat with in your new city.",
  strictFilters:
    "City and gender preference are strict: you only see people in your city whose preference includes you and who fit yours.",
  save: "Save",
  saving: "Saving…",
  saved: "Saved",
  cancel: "Cancel",
  back: "Back to flatmates",
  noProfile: {
    title: "Create your flatmate profile",
    body: "Matches appear once you tell us your city, budget and habits. Only compatible people in the same city can see your profile.",
  },
  mine: {
    title: "My flatmate profile",
    edit: "Edit profile",
    active: "Show my profile to matches",
    activeHint: "Turn this off to pause. You won't see matches while it is off.",
    paused: "Your profile is paused, so you are hidden from matches and the list below is empty.",
    requests: "Connect requests",
  },
  profile: {
    createTitle: "Create flatmate profile",
    editTitle: "Edit flatmate profile",
    intro: "Phone numbers and emails are never shown. People reach you only through a connect request you accept.",
    yourGender: "Your gender",
    yourGenderHint: "From your account. It cannot be changed here.",
    genderMissing: "Not set. Finish onboarding first.",
    city: "City",
    chooseCity: "Choose a city",
    areas: "Preferred areas",
    areasHint: "Optional. Leave empty if any area works.",
    noAreas: "No areas are listed for this city yet.",
    budgetMin: "Budget from (₹ a month)",
    budgetMax: "Budget up to (₹ a month)",
    moveDate: "Move date",
    preferredGender: "Preferred flatmate gender",
    foodHabit: "Food habits",
    smokes: "I smoke",
    okWithSmoker: "I'm fine living with a smoker",
    sleepSchedule: "Sleep schedule",
    workSchedule: "Work schedule",
    cleanliness: "Cleanliness",
    cleanlinessHint: "1 = relaxed, 5 = very tidy",
    guestsPolicy: "Guests",
    bio: "Short bio",
    bioHint: "A few lines about you and what you're looking for. Don't include a phone number or email.",
    isActive: "Show my profile to matches",
    delete: "Delete my flatmate profile",
    deleteQuestion: "Delete your flatmate profile?",
    deleteBody: "You will disappear from other people's matches. Existing chats stay open.",
    deleting: "Deleting…",
    deleted: "Flatmate profile deleted",
  },
  matches: {
    title: "Your matches",
    empty: "No matches yet",
    emptyBody: "Nobody compatible in your city right now. Widening your budget or areas only changes the score; city and gender preference decide who appears.",
    score: (score: number) => `${score}% match`,
    budget: "Budget",
    moveDate: "Moving",
    areas: "Areas",
    anyArea: "Any area",
    food: "Food",
    smoking: "Smoking",
    smokes: "Smokes",
    nonSmoker: "Non-smoker",
    sleep: "Sleep",
    work: "Work",
    cleanliness: "Cleanliness",
    cleanlinessValue: (value: number) => `${value} of 5`,
    guests: "Guests",
    previous: "Previous",
    next: "Next",
    pagination: "Match pages",
    unnamed: "Community member",
  },
  connect: {
    button: "Connect",
    title: (name: string) => `Connect with ${name}`,
    body: "They'll see your profile and this note. If they accept, a chat opens.",
    message: "Note (optional)",
    send: "Send request",
    sending: "Sending…",
    sent: "Connect request sent",
    pending: "Request pending",
    connected: "Connected",
    openChat: "Open chat",
  },
  requests: {
    pageTitle: "Flatmate connect requests",
    intro: "Accepting a request opens a chat with that person.",
    incoming: "Received",
    sent: "Sent",
    incomingEmpty: "No requests received yet.",
    sentEmpty: "You haven't sent any requests yet.",
    accept: "Accept",
    decline: "Decline",
    withdraw: "Withdraw",
    working: "Saving…",
    accepted: "Accepted. A chat is now open.",
    declined: "Request declined",
    withdrawn: "Request withdrawn",
    noMessage: "No note added.",
    from: (name: string) => `From ${name}`,
    to: (name: string) => `To ${name}`,
    status: { pending: "Pending", accepted: "Accepted", declined: "Declined", withdrawn: "Withdrawn" },
  },
  errors: {
    generic: "Something went wrong. Please try again.",
    notSignedIn: "Please sign in again.",
    invalid: "Check the form and try again.",
    city: "Choose a city.",
    areas: "Choose up to 20 areas.",
    budget: "Enter a whole amount in rupees.",
    budgetOrder: "The upper budget must be at least the lower budget.",
    moveDate: "Choose a valid move date.",
    choose: "Choose an option.",
    cleanliness: "Choose a value from 1 to 5.",
    bio: "Keep the bio under 1000 characters.",
    message: "Keep the note under 500 characters.",
    noProfile: "Create your flatmate profile first.",
    db: {
      not_authenticated: "Please sign in again.",
      onboarding_required: "Finish setting up your account first.",
      message_too_long: "Keep the note under 500 characters.",
      not_a_match: "You can't connect with this person. They may have paused their profile or no longer match.",
      already_connected: "You already have a request or connection with this person.",
      connection_not_found: "That request no longer exists.",
      connection_already_decided: "That request was already answered.",
      blocked: "You can't connect with this person.",
    },
  },
} as const;
